// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCharacInfo = "charac_info"

// CharacInfo mapped from table <charac_info>
type CharacInfo struct {
	MID                 int32     `gorm:"column:m_id;not null" json:"m_id"`
	CharacNo            int32     `gorm:"column:charac_no;primaryKey;autoIncrement:true" json:"charac_no"`
	CharacName          string    `gorm:"column:charac_name;not null" json:"charac_name"`
	Village             int32     `gorm:"column:village;not null;default:1" json:"village"`
	Job                 int32     `gorm:"column:job;not null" json:"job"`
	Lev                 int32     `gorm:"column:lev;not null;default:1" json:"lev"`
	Exp                 int32     `gorm:"column:exp;not null" json:"exp"`
	GrowType            int32     `gorm:"column:grow_type;not null" json:"grow_type"`
	HP                  int32     `gorm:"column:HP;not null" json:"HP"`
	MaxHP               int32     `gorm:"column:maxHP;not null" json:"maxHP"`
	MaxMP               int32     `gorm:"column:maxMP;not null" json:"maxMP"`
	PhyAttack           int32     `gorm:"column:phy_attack;not null" json:"phy_attack"`
	PhyDefense          int32     `gorm:"column:phy_defense;not null" json:"phy_defense"`
	MagAttack           int32     `gorm:"column:mag_attack;not null" json:"mag_attack"`
	MagDefense          int32     `gorm:"column:mag_defense;not null" json:"mag_defense"`
	ElementResist       []byte    `gorm:"column:element_resist;not null" json:"element_resist"`
	SpecProperty        []byte    `gorm:"column:spec_property;not null" json:"spec_property"`
	InvenWeight         int32     `gorm:"column:inven_weight;not null" json:"inven_weight"`
	HpRegen             int32     `gorm:"column:hp_regen;not null" json:"hp_regen"`
	MpRegen             int32     `gorm:"column:mp_regen;not null" json:"mp_regen"`
	MoveSpeed           int32     `gorm:"column:move_speed;not null" json:"move_speed"`
	AttackSpeed         int32     `gorm:"column:attack_speed;not null" json:"attack_speed"`
	CastSpeed           int32     `gorm:"column:cast_speed;not null" json:"cast_speed"`
	HitRecovery         int32     `gorm:"column:hit_recovery;not null" json:"hit_recovery"`
	Jump                int32     `gorm:"column:jump;not null" json:"jump"`
	CharacWeight        int32     `gorm:"column:charac_weight;not null" json:"charac_weight"`
	Fatigue             int32     `gorm:"column:fatigue;not null" json:"fatigue"`
	MaxFatigue          int32     `gorm:"column:max_fatigue;not null;default:70" json:"max_fatigue"`
	PremiumFatigue      int32     `gorm:"column:premium_fatigue;not null" json:"premium_fatigue"`
	MaxPremiumFatigue   int32     `gorm:"column:max_premium_fatigue;not null" json:"max_premium_fatigue"`
	CreateTime          time.Time `gorm:"column:create_time;not null;default:2021-11-19 00:00:00" json:"create_time"`
	LastPlayTime        time.Time `gorm:"column:last_play_time;not null;default:2021-11-19 00:00:00" json:"last_play_time"`
	DungeonClearPoint   int32     `gorm:"column:dungeon_clear_point;not null" json:"dungeon_clear_point"`
	DeleteTime          time.Time `gorm:"column:delete_time;not null;default:2021-11-19 00:00:00" json:"delete_time"`
	DeleteFlag          int32     `gorm:"column:delete_flag;not null" json:"delete_flag"`
	GuildID             int32     `gorm:"column:guild_id;not null" json:"guild_id"`
	GuildRight          int32     `gorm:"column:guild_right;not null" json:"guild_right"`
	MemberFlag          int32     `gorm:"column:member_flag;not null" json:"member_flag"`
	Sex                 int32     `gorm:"column:sex;not null;default:1" json:"sex"`
	ExpertJob           int32     `gorm:"column:expert_job;not null" json:"expert_job"`
	SkillTreeIndex      int32     `gorm:"column:skill_tree_index;not null;default:-1" json:"skill_tree_index"`
	LinkCharacNo        int32     `gorm:"column:link_charac_no;not null" json:"link_charac_no"`
	EventCharacLevel    int32     `gorm:"column:event_charac_level;not null" json:"event_charac_level"`
	GuildSecede         int32     `gorm:"column:guild_secede;not null" json:"guild_secede"`
	StartTime           int32     `gorm:"column:start_time;not null" json:"start_time"`
	FinishTime          int32     `gorm:"column:finish_time;not null" json:"finish_time"`
	CompetitionArea     int32     `gorm:"column:competition_area;not null;default:-1" json:"competition_area"`
	CompetitionPeriod   int32     `gorm:"column:competition_period;not null;default:-1" json:"competition_period"`
	MercenaryStartTime  int32     `gorm:"column:mercenary_start_time;not null" json:"mercenary_start_time"`
	MercenaryFinishTime int32     `gorm:"column:mercenary_finish_time;not null" json:"mercenary_finish_time"`
	MercenaryArea       int32     `gorm:"column:mercenary_area;not null;default:-1" json:"mercenary_area"`
	MercenaryPeriod     int32     `gorm:"column:mercenary_period;not null;default:-1" json:"mercenary_period"`
	VIP                 string    `gorm:"column:VIP;not null" json:"VIP"`
}

// TableName CharacInfo's table name
func (*CharacInfo) TableName() string {
	return TableNameCharacInfo
}
