// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAllowProxyUser = "allow_proxy_user"

// AllowProxyUser mapped from table <allow_proxy_user>
type AllowProxyUser struct {
	MID int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
}

// TableName AllowProxyUser's table name
func (*AllowProxyUser) TableName() string {
	return TableNameAllowProxyUser
}
