// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAutoPunishHackFullIP = "auto_punish_hack_full_ip"

// AutoPunishHackFullIP mapped from table <auto_punish_hack_full_ip>
type AutoPunishHackFullIP struct {
	OccDate     time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	HackType    int32     `gorm:"column:hack_type;primaryKey" json:"hack_type"`
	HackSubType int32     `gorm:"column:hack_sub_type;primaryKey" json:"hack_sub_type"`
	FullIP      string    `gorm:"column:full_ip;primaryKey" json:"full_ip"`
	Cnt         int32     `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName AutoPunishHackFullIP's table name
func (*AutoPunishHackFullIP) TableName() string {
	return TableNameAutoPunishHackFullIP
}
