// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAutoPunishHackInfo = "auto_punish_hack_info"

// AutoPunishHackInfo mapped from table <auto_punish_hack_info>
type AutoPunishHackInfo struct {
	HackType    int32     `gorm:"column:hack_type;primaryKey" json:"hack_type"`
	Cnt         int32     `gorm:"column:cnt;not null" json:"cnt"`
	Etc         int64     `gorm:"column:etc;not null" json:"etc"`
	RegDate     time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
	ApplyFlag   int32     `gorm:"column:apply_flag;primaryKey" json:"apply_flag"`
	HackSubType int32     `gorm:"column:hack_sub_type;primaryKey" json:"hack_sub_type"`
	HackSubCnt  int32     `gorm:"column:hack_sub_cnt;not null" json:"hack_sub_cnt"`
	IPCnt       int32     `gorm:"column:ip_cnt;not null" json:"ip_cnt"`
}

// TableName AutoPunishHackInfo's table name
func (*AutoPunishHackInfo) TableName() string {
	return TableNameAutoPunishHackInfo
}
