// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAutoPunishSecondUser = "auto_punish_second_user"

// AutoPunishSecondUser mapped from table <auto_punish_second_user>
type AutoPunishSecondUser struct {
	MID            int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime        time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	TotalTradeCnt  int32     `gorm:"column:total_trade_cnt;not null" json:"total_trade_cnt"`
	TradeCnt       int32     `gorm:"column:trade_cnt;not null" json:"trade_cnt"`
	TotalTradeGold int64     `gorm:"column:total_trade_gold;not null" json:"total_trade_gold"`
	TradeGold      int64     `gorm:"column:trade_gold;not null" json:"trade_gold"`
	PunishFlag     int32     `gorm:"column:punish_flag;not null" json:"punish_flag"`
}

// TableName AutoPunishSecondUser's table name
func (*AutoPunishSecondUser) TableName() string {
	return TableNameAutoPunishSecondUser
}
