// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChurnMemberInfo = "churn_member_info"

// ChurnMemberInfo mapped from table <churn_member_info>
type ChurnMemberInfo struct {
	MID              int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	AccrueCera       int32  `gorm:"column:accrue_cera;not null" json:"accrue_cera"`
	PlayInfo         string `gorm:"column:play_info;not null" json:"play_info"`
	FirstRewardTime  int32  `gorm:"column:first_reward_time;not null" json:"first_reward_time"`
	LastRewardTime   int32  `gorm:"column:last_reward_time;not null" json:"last_reward_time"`
	ServerID         int32  `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo         int32  `gorm:"column:charac_no;not null" json:"charac_no"`
	ItemID           int32  `gorm:"column:item_id;not null" json:"item_id"`
	AddInfo          int32  `gorm:"column:add_info;not null" json:"add_info"`
	LuckPoint        int32  `gorm:"column:luck_point;not null" json:"luck_point"`
	LastUpdateTime   int32  `gorm:"column:last_update_time;not null" json:"last_update_time"`
	SecondRewardTime int32  `gorm:"column:second_reward_time;not null" json:"second_reward_time"`
	QuestTime        int32  `gorm:"column:quest_time;not null" json:"quest_time"`
}

// TableName ChurnMemberInfo's table name
func (*ChurnMemberInfo) TableName() string {
	return TableNameChurnMemberInfo
}
