// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChurnRewardHistory = "churn_reward_history"

// ChurnRewardHistory mapped from table <churn_reward_history>
type ChurnRewardHistory struct {
	MID         int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime     time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerID    int32     `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo    int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	ItemID      int32     `gorm:"column:item_id;not null" json:"item_id"`
	AddInfo     int32     `gorm:"column:add_info;not null" json:"add_info"`
	LuckPoint   int32     `gorm:"column:luck_point;not null" json:"luck_point"`
	RewardOrder int32     `gorm:"column:reward_order;not null" json:"reward_order"`
	Cera        int32     `gorm:"column:cera;not null" json:"cera"`
}

// TableName ChurnRewardHistory's table name
func (*ChurnRewardHistory) TableName() string {
	return TableNameChurnRewardHistory
}
