// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChurnRewardManager = "churn_reward_manager"

// ChurnRewardManager mapped from table <churn_reward_manager>
type ChurnRewardManager struct {
	MinDay    int32 `gorm:"column:min_day;primaryKey" json:"min_day"`
	MaxDay    int32 `gorm:"column:max_day;primaryKey" json:"max_day"`
	MinVal    int32 `gorm:"column:min_val;primaryKey" json:"min_val"`
	MaxVal    int32 `gorm:"column:max_val;primaryKey" json:"max_val"`
	ItemID    int32 `gorm:"column:item_id;not null" json:"item_id"`
	AddInfo   int32 `gorm:"column:add_info;not null" json:"add_info"`
	LuckPoint int32 `gorm:"column:luck_point;not null" json:"luck_point"`
	QuestID   int32 `gorm:"column:quest_id;primaryKey" json:"quest_id"`
}

// TableName ChurnRewardManager's table name
func (*ChurnRewardManager) TableName() string {
	return TableNameChurnRewardManager
}
