// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfEventEntry = "dnf_event_entry"

// DnfEventEntry mapped from table <dnf_event_entry>
type DnfEventEntry struct {
	EventID    int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccDate    time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
	ServerID   int32     `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo   int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	ObtainDate time.Time `gorm:"column:obtain_date;not null" json:"obtain_date"`
}

// TableName DnfEventEntry's table name
func (*DnfEventEntry) TableName() string {
	return TableNameDnfEventEntry
}
