// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventServerMessage = "event_server_message"

// EventServerMessage mapped from table <event_server_message>
type EventServerMessage struct {
	ServerInfo   int32  `gorm:"column:server_info;not null" json:"server_info"`
	ChannelNo    int32  `gorm:"column:channel_no;not null" json:"channel_no"`
	Kind         string `gorm:"column:kind;not null" json:"kind"`
	MessageIndex string `gorm:"column:message_index;not null" json:"message_index"`
	CharacName   string `gorm:"column:charac_name;not null" json:"charac_name"`
	Message      string `gorm:"column:message;not null" json:"message"`
	UpdateTime   int32  `gorm:"column:update_time;not null" json:"update_time"`
}

// TableName EventServerMessage's table name
func (*EventServerMessage) TableName() string {
	return TableNameEventServerMessage
}
