// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGmManifest = "gm_manifest"

// GmManifest mapped from table <gm_manifest>
type GmManifest struct {
	MID   int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	Level int32 `gorm:"column:level;not null" json:"level"`
}

// TableName GmManifest's table name
func (*GmManifest) TableName() string {
	return TableNameGmManifest
}
