// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHackCleanpadRatioInfo = "hack_cleanpad_ratio_info"

// HackCleanpadRatioInfo mapped from table <hack_cleanpad_ratio_info>
type HackCleanpadRatioInfo struct {
	HackType int32     `gorm:"column:hack_type;primaryKey" json:"hack_type"`
	Value    int32     `gorm:"column:value;not null" json:"value"`
	RegDate  time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
}

// TableName HackCleanpadRatioInfo's table name
func (*HackCleanpadRatioInfo) TableName() string {
	return TableNameHackCleanpadRatioInfo
}
