// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHumanCertifyTryCount = "human_certify_try_count"

// HumanCertifyTryCount mapped from table <human_certify_try_count>
type HumanCertifyTryCount struct {
	MID    int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	Count_ int32 `gorm:"column:count;not null" json:"count"`
}

// TableName HumanCertifyTryCount's table name
func (*HumanCertifyTryCount) TableName() string {
	return TableNameHumanCertifyTryCount
}
