// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIPMonitorPunish = "ip_monitor_punish"

// IPMonitorPunish mapped from table <ip_monitor_punish>
type IPMonitorPunish struct {
	IP        string    `gorm:"column:ip;primaryKey" json:"ip"`
	Type      int32     `gorm:"column:type;primaryKey" json:"type"`
	MIDCnt    int32     `gorm:"column:m_id_cnt;not null" json:"m_id_cnt"`
	StartTime time.Time `gorm:"column:start_time;not null" json:"start_time"`
	EndTime   time.Time `gorm:"column:end_time;not null" json:"end_time"`
}

// TableName IPMonitorPunish's table name
func (*IPMonitorPunish) TableName() string {
	return TableNameIPMonitorPunish
}
