// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogGrowth = "log_growth"

// LogGrowth mapped from table <log_growth>
type LogGrowth struct {
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServerInfo int32     `gorm:"column:server_info;primaryKey" json:"server_info"`
	CharacNo   int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	CharacName string    `gorm:"column:charac_name;not null" json:"charac_name"`
	Job        int32     `gorm:"column:job;not null" json:"job"`
	GrowType   int32     `gorm:"column:grow_type;not null" json:"grow_type"`
	OccTime    time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
}

// TableName LogGrowth's table name
func (*LogGrowth) TableName() string {
	return TableNameLogGrowth
}
