// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLogQueryDbmwRef = "log_query_dbmw_ref"

// LogQueryDbmwRef mapped from table <log_query_dbmw_ref>
type LogQueryDbmwRef struct {
	QueryHash string `gorm:"column:query_hash;not null" json:"query_hash"`
	QID       int32  `gorm:"column:q_id;primaryKey;autoIncrement:true" json:"q_id"`
	Query     string `gorm:"column:query;not null" json:"query"`
}

// TableName LogQueryDbmwRef's table name
func (*LogQueryDbmwRef) TableName() string {
	return TableNameLogQueryDbmwRef
}
