// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLogQueryRef = "log_query_ref"

// LogQueryRef mapped from table <log_query_ref>
type LogQueryRef struct {
	QueryHash string `gorm:"column:query_hash;not null" json:"query_hash"`
	QID       int32  `gorm:"column:q_id;primaryKey;autoIncrement:true" json:"q_id"`
	Query     string `gorm:"column:query;not null" json:"query"`
}

// TableName LogQueryRef's table name
func (*LogQueryRef) TableName() string {
	return TableNameLogQueryRef
}
