// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLoginHistory = "login_history"

// LoginHistory mapped from table <login_history>
type LoginHistory struct {
	MID     int32 `gorm:"column:m_id;not null" json:"m_id"`
	OccTime int32 `gorm:"column:occ_time;not null" json:"occ_time"`
	Trigger int32 `gorm:"column:trigger;not null" json:"trigger"`
}

// TableName LoginHistory's table name
func (*LoginHistory) TableName() string {
	return TableNameLoginHistory
}
