// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberPremium = "member_premium"

// MemberPremium mapped from table <member_premium>
type MemberPremium struct {
	EventID      int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	PreType      int32     `gorm:"column:pre_type;primaryKey" json:"pre_type"`
	ServerID     int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	MID          int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServiceStart time.Time `gorm:"column:service_start;primaryKey" json:"service_start"`
	ServiceEnd   time.Time `gorm:"column:service_end;not null" json:"service_end"`
}

// TableName MemberPremium's table name
func (*MemberPremium) TableName() string {
	return TableNameMemberPremium
}
