// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberDoubtTrade = "member_doubt_trade"

// MemberDoubtTrade mapped from table <member_doubt_trade>
type MemberDoubtTrade struct {
	MID            int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;not null" json:"last_update_time"`
	OverCount      int32     `gorm:"column:over_count;not null" json:"over_count"`
}

// TableName MemberDoubtTrade's table name
func (*MemberDoubtTrade) TableName() string {
	return TableNameMemberDoubtTrade
}
