// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberPlayInfoDel = "member_play_info_del"

// MemberPlayInfoDel mapped from table <member_play_info_del>
type MemberPlayInfoDel struct {
	Sdate        time.Time `gorm:"column:sdate;primaryKey" json:"sdate"`
	OccDate      time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	MID          int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	PlayTime     int32     `gorm:"column:play_time;not null" json:"play_time"`
	PlayCount    int32     `gorm:"column:play_count;not null" json:"play_count"`
	TradeCnt     int32     `gorm:"column:trade_cnt;not null" json:"trade_cnt"`
	Exp          int32     `gorm:"column:exp;not null" json:"exp"`
	UsedFatigue  int32     `gorm:"column:used_fatigue;not null" json:"used_fatigue"`
	IP           string    `gorm:"column:ip;not null" json:"ip"`
	LastPlayTime int32     `gorm:"column:last_play_time;not null" json:"last_play_time"`
	PcbangFlag   int32     `gorm:"column:pcbang_flag;not null" json:"pcbang_flag"`
	EndIP        string    `gorm:"column:end_ip;not null" json:"end_ip"`
	TingCount    int32     `gorm:"column:ting_count;not null" json:"ting_count"`
	MacAddr      string    `gorm:"column:mac_addr;not null" json:"mac_addr"`
	ServerID     int32     `gorm:"column:server_id;not null" json:"server_id"`
}

// TableName MemberPlayInfoDel's table name
func (*MemberPlayInfoDel) TableName() string {
	return TableNameMemberPlayInfoDel
}
