// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberMousepass = "member_mousepass"

// MemberMousepass mapped from table <member_mousepass>
type MemberMousepass struct {
	MID          int32     `gorm:"column:m_id;not null" json:"m_id"`
	Mousepass    string    `gorm:"column:mousepass;not null" json:"mousepass"`
	OccTime      time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	FailCnt      int32     `gorm:"column:fail_cnt;not null" json:"fail_cnt"`
	CancelCnt    int32     `gorm:"column:cancel_cnt;not null" json:"cancel_cnt"`
	VersionInfo  string    `gorm:"column:version_info;not null;default:1" json:"version_info"`
	ValidityTime int32     `gorm:"column:validity_time;not null" json:"validity_time"`
	RewardTime   int32     `gorm:"column:reward_time;not null" json:"reward_time"`
	EnableFlag   string    `gorm:"column:enable_flag;not null" json:"enable_flag"`
}

// TableName MemberMousepass's table name
func (*MemberMousepass) TableName() string {
	return TableNameMemberMousepass
}
