// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberGameOption = "member_game_option"

// MemberGameOption mapped from table <member_game_option>
type MemberGameOption struct {
	MID              int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	Option1          []byte `gorm:"column:option_1;not null" json:"option_1"`
	Option2          []byte `gorm:"column:option_2;not null" json:"option_2"`
	Option3          []byte `gorm:"column:option_3;not null" json:"option_3"`
	ShortcutEmoticon []byte `gorm:"column:shortcut_emoticon;not null" json:"shortcut_emoticon"`
}

// TableName MemberGameOption's table name
func (*MemberGameOption) TableName() string {
	return TableNameMemberGameOption
}
