// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberSecurityCardHistory = "member_security_card_history"

// MemberSecurityCardHistory mapped from table <member_security_card_history>
type MemberSecurityCardHistory struct {
	OccTime    time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ModifyType int32     `gorm:"column:modify_type;not null" json:"modify_type"`
}

// TableName MemberSecurityCardHistory's table name
func (*MemberSecurityCardHistory) TableName() string {
	return TableNameMemberSecurityCardHistory
}
