// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberCaptchaInfo = "member_captcha_info"

// MemberCaptchaInfo mapped from table <member_captcha_info>
type MemberCaptchaInfo struct {
	MID       int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	CertTime  int32 `gorm:"column:cert_time;not null" json:"cert_time"`
	FailCount int32 `gorm:"column:fail_count;not null" json:"fail_count"`
}

// TableName MemberCaptchaInfo's table name
func (*MemberCaptchaInfo) TableName() string {
	return TableNameMemberCaptchaInfo
}
