// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberLogin = "member_login"

// MemberLogin mapped from table <member_login>
type MemberLogin struct {
	MID              int32   `gorm:"column:m_id;primaryKey" json:"m_id"`
	LoginTime        int32   `gorm:"column:login_time;not null" json:"login_time"`
	ExpireTime       int32   `gorm:"column:expire_time;not null" json:"expire_time"`
	LastPlayTime     int32   `gorm:"column:last_play_time;not null" json:"last_play_time"`
	TotalAccountFail int32   `gorm:"column:total_account_fail;not null" json:"total_account_fail"`
	AccountFail      int32   `gorm:"column:account_fail;not null" json:"account_fail"`
	ReportCnt        int32   `gorm:"column:report_cnt;not null" json:"report_cnt"`
	ReliableFlag     int32   `gorm:"column:reliable_flag;not null" json:"reliable_flag"`
	TradeGoldDaily   int32   `gorm:"column:trade_gold_daily;not null" json:"trade_gold_daily"`
	LastGiftTime     int32   `gorm:"column:last_gift_time;not null" json:"last_gift_time"`
	GiftCnt          int32   `gorm:"column:gift_cnt;not null" json:"gift_cnt"`
	LoginIP          string  `gorm:"column:login_ip;not null" json:"login_ip"`
	SecurityFlag     int32   `gorm:"column:security_flag;not null" json:"security_flag"`
	PowerSide        int32   `gorm:"column:power_side;not null" json:"power_side"`
	DungeonGainGold  int32   `gorm:"column:dungeon_gain_gold;not null" json:"dungeon_gain_gold"`
	SchoolID         int32   `gorm:"column:school_id;not null" json:"school_id"`
	Rating           float32 `gorm:"column:rating;not null" json:"rating"`
	CleanpadPoint    int32   `gorm:"column:cleanpad_point;not null" json:"cleanpad_point"`
	TutorialSkipable string  `gorm:"column:tutorial_skipable;not null;default:0" json:"tutorial_skipable"`
	EventCharacFlag  int32   `gorm:"column:event_charac_flag;not null" json:"event_charac_flag"`
	GarenaTokenKey   int64   `gorm:"column:garena_token_key;not null" json:"garena_token_key"`
}

// TableName MemberLogin's table name
func (*MemberLogin) TableName() string {
	return TableNameMemberLogin
}
