// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberMousepassHistory = "member_mousepass_history"

// MemberMousepassHistory mapped from table <member_mousepass_history>
type MemberMousepassHistory struct {
	OccTime      time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	MID          int32     `gorm:"column:m_id;not null" json:"m_id"`
	PreMousepass string    `gorm:"column:pre_mousepass;not null" json:"pre_mousepass"`
	ModifyType   int32     `gorm:"column:modify_type;not null" json:"modify_type"`
}

// TableName MemberMousepassHistory's table name
func (*MemberMousepassHistory) TableName() string {
	return TableNameMemberMousepassHistory
}
