// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNexonNoneMemnerRestriction = "nexon_none_memner_restriction"

// NexonNoneMemnerRestriction mapped from table <nexon_none_memner_restriction>
type NexonNoneMemnerRestriction struct {
	MID            int32     `gorm:"column:m_id;not null" json:"m_id"`
	CharacID       int32     `gorm:"column:charac_id;not null" json:"charac_id"`
	LastTradeTime  time.Time `gorm:"column:last_trade_time;not null" json:"last_trade_time"`
	TotalTradeGold int32     `gorm:"column:total_trade_gold;not null" json:"total_trade_gold"`
	TradeCount     int32     `gorm:"column:trade_count;not null" json:"trade_count"`
	NexonUser      int32     `gorm:"column:nexon_user;not null" json:"nexon_user"`
}

// TableName NexonNoneMemnerRestriction's table name
func (*NexonNoneMemnerRestriction) TableName() string {
	return TableNameNexonNoneMemnerRestriction
}
