// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVillageAttackedServerTimeRank = "village_attacked_server_time_rank"

// VillageAttackedServerTimeRank mapped from table <village_attacked_server_time_rank>
type VillageAttackedServerTimeRank struct {
	ServerInfo int32     `gorm:"column:server_info;primaryKey" json:"server_info"`
	OccDate    time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	ClearTime  int32     `gorm:"column:clear_time;not null" json:"clear_time"`
	Rank       int32     `gorm:"column:rank;not null" json:"rank"`
}

// TableName VillageAttackedServerTimeRank's table name
func (*VillageAttackedServerTimeRank) TableName() string {
	return TableNameVillageAttackedServerTimeRank
}
