// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVillageAttackedServerPointRank = "village_attacked_server_point_rank"

// VillageAttackedServerPointRank mapped from table <village_attacked_server_point_rank>
type VillageAttackedServerPointRank struct {
	ServerInfo   int32     `gorm:"column:server_info;primaryKey" json:"server_info"`
	OccDate      time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	HuntingPoint int32     `gorm:"column:hunting_point;not null" json:"hunting_point"`
	Rank         int32     `gorm:"column:rank;not null" json:"rank"`
}

// TableName VillageAttackedServerPointRank's table name
func (*VillageAttackedServerPointRank) TableName() string {
	return TableNameVillageAttackedServerPointRank
}
