// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVillageAttackedCharacPointRank = "village_attacked_charac_point_rank"

// VillageAttackedCharacPointRank mapped from table <village_attacked_charac_point_rank>
type VillageAttackedCharacPointRank struct {
	ServerInfo   int32     `gorm:"column:server_info;primaryKey" json:"server_info"`
	OccDate      time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	CharacNo     int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	HuntingPoint int32     `gorm:"column:hunting_point;not null" json:"hunting_point"`
	Rank         int32     `gorm:"column:rank;not null" json:"rank"`
}

// TableName VillageAttackedCharacPointRank's table name
func (*VillageAttackedCharacPointRank) TableName() string {
	return TableNameVillageAttackedCharacPointRank
}
