// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCashTransaction = "cash_transaction"

// CashTransaction mapped from table <cash_transaction>
type CashTransaction struct {
	TranID int64  `gorm:"column:tran_id;primaryKey;autoIncrement:true" json:"tran_id"`
	Dummy  string `gorm:"column:dummy;not null" json:"dummy"`
}

// TableName CashTransaction's table name
func (*CashTransaction) TableName() string {
	return TableNameCashTransaction
}
