// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCashCeraPoint = "cash_cera_point"

// CashCeraPoint mapped from table <cash_cera_point>
type CashCeraPoint struct {
	Account   string    `gorm:"column:account;primaryKey" json:"account"`
	CeraPoint int32     `gorm:"column:cera_point;not null" json:"cera_point"`
	RegDate   time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
	ModDate   time.Time `gorm:"column:mod_date;not null" json:"mod_date"`
}

// TableName CashCeraPoint's table name
func (*CashCeraPoint) TableName() string {
	return TableNameCashCeraPoint
}
