// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCashCera = "cash_cera"

// CashCera mapped from table <cash_cera>
type CashCera struct {
	Account string    `gorm:"column:account;primaryKey" json:"account"`
	Cera    int32     `gorm:"column:cera;not null" json:"cera"`
	ModTran int64     `gorm:"column:mod_tran;not null" json:"mod_tran"`
	ModDate time.Time `gorm:"column:mod_date;not null" json:"mod_date"`
	RegDate time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
}

// TableName CashCera's table name
func (*CashCera) TableName() string {
	return TableNameCashCera
}
