// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogPointHistory = "log_point_history"

// LogPointHistory mapped from table <log_point_history>
type LogPointHistory struct {
	No             int32     `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	AccountID      string    `gorm:"column:account_id;not null" json:"account_id"`
	CharacID       string    `gorm:"column:charac_id;not null" json:"charac_id"`
	CeraPoint      int32     `gorm:"column:cera_point;not null" json:"cera_point"`
	Command        string    `gorm:"column:command;not null;comment:A(add), U(use)" json:"command"` // A(add), U(use)
	ChargeType     int32     `gorm:"column:charge_type;not null" json:"charge_type"`
	FreeChargeType int32     `gorm:"column:free_charge_type;not null" json:"free_charge_type"`
	ItemID         int32     `gorm:"column:item_id;not null" json:"item_id"`
	QueryUser      string    `gorm:"column:query_user;not null;default:None" json:"query_user"`
	RegDate        time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
}

// TableName LogPointHistory's table name
func (*LogPointHistory) TableName() string {
	return TableNameLogPointHistory
}
