// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogItemRefundHistory = "log_item_refund_history"

// LogItemRefundHistory mapped from table <log_item_refund_history>
type LogItemRefundHistory struct {
	PfRelID        int32     `gorm:"column:pf_rel_id;primaryKey;autoIncrement:true" json:"pf_rel_id"`
	PurchaseTranID int64     `gorm:"column:purchase_tran_id;not null" json:"purchase_tran_id"`
	RechargeTranID int64     `gorm:"column:recharge_tran_id;not null" json:"recharge_tran_id"`
	AccountID      string    `gorm:"column:account_id;not null" json:"account_id"`
	OccDate        time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
	Reason         string    `gorm:"column:reason;not null" json:"reason"`
	AdminID        string    `gorm:"column:admin_id;not null" json:"admin_id"`
	QueryUser      string    `gorm:"column:query_user;not null;default:None" json:"query_user"`
}

// TableName LogItemRefundHistory's table name
func (*LogItemRefundHistory) TableName() string {
	return TableNameLogItemRefundHistory
}
