// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogTransactionHistory = "log_transaction_history"

// LogTransactionHistory mapped from table <log_transaction_history>
type LogTransactionHistory struct {
	TranID   int64     `gorm:"column:tran_id;primaryKey" json:"tran_id"`
	TranType int32     `gorm:"column:tran_type;not null" json:"tran_type"`
	OccDate  time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
}

// TableName LogTransactionHistory's table name
func (*LogTransactionHistory) TableName() string {
	return TableNameLogTransactionHistory
}
