// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberPunishInfoArsMail = "member_punish_info_ars_mail"

// MemberPunishInfoArsMail mapped from table <member_punish_info_ars_mail>
type MemberPunishInfoArsMail struct {
	No         int32     `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	MID        int32     `gorm:"column:m_id;not null" json:"m_id"`
	PunishType int32     `gorm:"column:punish_type;not null" json:"punish_type"`
	ApplyFlag  int32     `gorm:"column:apply_flag;not null" json:"apply_flag"`
	OccTime    time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	SendTime   time.Time `gorm:"column:send_time;not null" json:"send_time"`
}

// TableName MemberPunishInfoArsMail's table name
func (*MemberPunishInfoArsMail) TableName() string {
	return TableNameMemberPunishInfoArsMail
}
