// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberPunishInfo = "member_punish_info"

// MemberPunishInfo mapped from table <member_punish_info>
type MemberPunishInfo struct {
	MID         int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	PunishType  int32     `gorm:"column:punish_type;primaryKey" json:"punish_type"`
	OccTime     time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	PunishValue int32     `gorm:"column:punish_value;not null" json:"punish_value"`
	ApplyFlag   int32     `gorm:"column:apply_flag;not null" json:"apply_flag"`
	StartTime   time.Time `gorm:"column:start_time;not null" json:"start_time"`
	EndTime     time.Time `gorm:"column:end_time;not null" json:"end_time"`
	AdminID     string    `gorm:"column:admin_id;not null" json:"admin_id"`
	Reason      string    `gorm:"column:reason;not null" json:"reason"`
}

// TableName MemberPunishInfo's table name
func (*MemberPunishInfo) TableName() string {
	return TableNameMemberPunishInfo
}
