// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberEnvLog = "member_env_log"

// MemberEnvLog mapped from table <member_env_log>
type MemberEnvLog struct {
	MID     int32     `gorm:"column:m_id;not null" json:"m_id"`
	MacAddr string    `gorm:"column:mac_addr;not null" json:"mac_addr"`
	Log     string    `gorm:"column:log;not null" json:"log"`
	OccTime time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
}

// TableName MemberEnvLog's table name
func (*MemberEnvLog) TableName() string {
	return TableNameMemberEnvLog
}
