// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberSecurityGrade = "member_security_grade"

// MemberSecurityGrade mapped from table <member_security_grade>
type MemberSecurityGrade struct {
	MID                      int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	LastVisitTime            time.Time `gorm:"column:last_visit_time;not null" json:"last_visit_time"`
	PassFailCnt              int32     `gorm:"column:pass_fail_cnt;not null" json:"pass_fail_cnt"`
	LastVaccineDate          time.Time `gorm:"column:last_vaccine_date;not null" json:"last_vaccine_date"`
	LastWindowDate           time.Time `gorm:"column:last_window_date;not null" json:"last_window_date"`
	GoblinPassMod            time.Time `gorm:"column:goblin_pass_mod;not null" json:"goblin_pass_mod"`
	GoblinFailCnt            int32     `gorm:"column:goblin_fail_cnt;not null" json:"goblin_fail_cnt"`
	SecurityCardReg          time.Time `gorm:"column:security_card_reg;not null" json:"security_card_reg"`
	SecurityCardFailCnt      int32     `gorm:"column:security_card_fail_cnt;not null" json:"security_card_fail_cnt"`
	MOptReg                  time.Time `gorm:"column:m_opt_reg;not null" json:"m_opt_reg"`
	PcOptReg                 time.Time `gorm:"column:pc_opt_reg;not null" json:"pc_opt_reg"`
	BlackIPTryTime           time.Time `gorm:"column:black_ip_try_time;not null" json:"black_ip_try_time"`
	LinearPassFailCnt        int32     `gorm:"column:linear_pass_fail_cnt;not null" json:"linear_pass_fail_cnt"`
	LastPassFailTime         int32     `gorm:"column:last_pass_fail_time;not null" json:"last_pass_fail_time"`
	LastCheckTime            time.Time `gorm:"column:last_check_time;not null" json:"last_check_time"`
	PassModifyCheck          time.Time `gorm:"column:pass_modify_check;not null" json:"pass_modify_check"`
	MemberPcReg              time.Time `gorm:"column:member_pc_reg;not null" json:"member_pc_reg"`
	GatekeeperOtpReg         time.Time `gorm:"column:gatekeeper_otp_reg;not null" json:"gatekeeper_otp_reg"`
	GoblinValidityTime       int32     `gorm:"column:goblin_validity_time;not null" json:"goblin_validity_time"`
	SecurityCardValidityTime int32     `gorm:"column:security_card_validity_time;not null" json:"security_card_validity_time"`
	ValidityIP               string    `gorm:"column:validity_ip;not null" json:"validity_ip"`
	CargopadStatus           int32     `gorm:"column:cargopad_status;not null" json:"cargopad_status"`
	CargopadMod              time.Time `gorm:"column:cargopad_mod;not null" json:"cargopad_mod"`
	CargopadValidityTime     int32     `gorm:"column:cargopad_validity_time;not null" json:"cargopad_validity_time"`
}

// TableName MemberSecurityGrade's table name
func (*MemberSecurityGrade) TableName() string {
	return TableNameMemberSecurityGrade
}
