// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAssertManager = "assert_manager"

// AssertManager mapped from table <assert_manager>
type AssertManager struct {
	FileName string `gorm:"column:file_name;primaryKey" json:"file_name"`
	FileLine int32  `gorm:"column:file_line;primaryKey" json:"file_line"`
	Reason   string `gorm:"column:reason;not null" json:"reason"`
	Cnt      int32  `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName AssertManager's table name
func (*AssertManager) TableName() string {
	return TableNameAssertManager
}
