// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCaptchaInvalidRequestType = "captcha_invalid_request_type"

// CaptchaInvalidRequestType mapped from table <captcha_invalid_request_type>
type CaptchaInvalidRequestType struct {
	Type     int32  `gorm:"column:type;primaryKey;autoIncrement:true" json:"type"`
	TypeDesc string `gorm:"column:type_desc;not null" json:"type_desc"`
}

// TableName CaptchaInvalidRequestType's table name
func (*CaptchaInvalidRequestType) TableName() string {
	return TableNameCaptchaInvalidRequestType
}
