// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCaptchaInvalidRequest = "captcha_invalid_request"

// CaptchaInvalidRequest mapped from table <captcha_invalid_request>
type CaptchaInvalidRequest struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MID         int32     `gorm:"column:m_id;not null" json:"m_id"`
	RequestType int32     `gorm:"column:request_type;not null" json:"request_type"`
	OccTime     time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
}

// TableName CaptchaInvalidRequest's table name
func (*CaptchaInvalidRequest) TableName() string {
	return TableNameCaptchaInvalidRequest
}
