// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCaptchaInfo = "captcha_info"

// CaptchaInfo mapped from table <captcha_info>
type CaptchaInfo struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OccTime                time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	TotalTryCount          int32     `gorm:"column:total_try_count;not null" json:"total_try_count"`
	SuccessCount           int32     `gorm:"column:success_count;not null" json:"success_count"`
	FailCount              int32     `gorm:"column:fail_count;not null" json:"fail_count"`
	BlockCount             int32     `gorm:"column:block_count;not null" json:"block_count"`
	IncompleteRequestCount int32     `gorm:"column:incomplete_request_count;not null" json:"incomplete_request_count"`
	InvalidRequestCount    int32     `gorm:"column:invalid_request_count;not null" json:"invalid_request_count"`
}

// TableName CaptchaInfo's table name
func (*CaptchaInfo) TableName() string {
	return TableNameCaptchaInfo
}
