// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCollectInterval = "collect_interval"

// CollectInterval mapped from table <collect_interval>
type CollectInterval struct {
	StartTime time.Time `gorm:"column:start_time" json:"start_time"`
	EndTime   time.Time `gorm:"column:end_time" json:"end_time"`
	Value     int32     `gorm:"column:value;default:60" json:"value"`
}

// TableName CollectInterval's table name
func (*CollectInterval) TableName() string {
	return TableNameCollectInterval
}
