// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommonIndexDaily = "common_index_daily"

// CommonIndexDaily mapped from table <common_index_daily>
type CommonIndexDaily struct {
	OccDate           time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	ServerGroup       int32     `gorm:"column:server_group;primaryKey" json:"server_group"`
	SpecID            int32     `gorm:"column:spec_id;primaryKey" json:"spec_id"`
	ShareRate         int32     `gorm:"column:share_rate;not null" json:"share_rate"`
	CrashVillage      int32     `gorm:"column:crash_village;not null" json:"crash_village"`
	CrashDungeon      int32     `gorm:"column:crash_dungeon;not null" json:"crash_dungeon"`
	CrashChallenge    int32     `gorm:"column:crash_challenge;not null" json:"crash_challenge"`
	CrashWararea      int32     `gorm:"column:crash_wararea;not null" json:"crash_wararea"`
	CrashFightVillage int32     `gorm:"column:crash_fight_village;not null" json:"crash_fight_village"`
	CrashDeadTower    int32     `gorm:"column:crash_dead_tower;not null" json:"crash_dead_tower"`
}

// TableName CommonIndexDaily's table name
func (*CommonIndexDaily) TableName() string {
	return TableNameCommonIndexDaily
}
