// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommonIndex = "common_index"

// CommonIndex mapped from table <common_index>
type CommonIndex struct {
	SpecID              int32     `gorm:"column:spec_id;not null" json:"spec_id"`
	OccTime             time.Time `gorm:"column:occ_time" json:"occ_time"`
	ServerGroup         int32     `gorm:"column:server_group;not null" json:"server_group"`
	ShareRate           int32     `gorm:"column:share_rate" json:"share_rate"`
	CrashCount          int32     `gorm:"column:crash_count" json:"crash_count"`
	VillageToDungeonLag int32     `gorm:"column:village_to_dungeon_lag;not null" json:"village_to_dungeon_lag"`
	DungeonToVillageLag int32     `gorm:"column:dungeon_to_village_lag;not null" json:"dungeon_to_village_lag"`
	CrashVillage        int32     `gorm:"column:crash_village;not null" json:"crash_village"`
	CrashDungeon        int32     `gorm:"column:crash_dungeon;not null" json:"crash_dungeon"`
	CrashChallenge      int32     `gorm:"column:crash_challenge;not null" json:"crash_challenge"`
	CrashWararea        int32     `gorm:"column:crash_wararea;not null" json:"crash_wararea"`
	CrashFightVillage   int32     `gorm:"column:crash_fight_village;not null" json:"crash_fight_village"`
	CrashDeadTower      int32     `gorm:"column:crash_dead_tower;not null" json:"crash_dead_tower"`
	CrashChannel        int32     `gorm:"column:crash_channel;not null" json:"crash_channel"`
	CrashChaos          int32     `gorm:"column:crash_chaos;not null" json:"crash_chaos"`
	CrashLoad           int32     `gorm:"column:crash_load;not null" json:"crash_load"`
}

// TableName CommonIndex's table name
func (*CommonIndex) TableName() string {
	return TableNameCommonIndex
}
