// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeadTowerLagIndexDaily = "dead_tower_lag_index_daily"

// DeadTowerLagIndexDaily mapped from table <dead_tower_lag_index_daily>
type DeadTowerLagIndexDaily struct {
	OccDate             time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	SpecID              int32     `gorm:"column:spec_id;primaryKey" json:"spec_id"`
	WinFps              int32     `gorm:"column:win_fps;not null" json:"win_fps"`
	WinFpsCnt           int32     `gorm:"column:win_fps_cnt;not null" json:"win_fps_cnt"`
	FullFps             int32     `gorm:"column:full_fps;not null" json:"full_fps"`
	FullFpsCnt          int32     `gorm:"column:full_fps_cnt;not null" json:"full_fps_cnt"`
	FullWinFps          int32     `gorm:"column:full_win_fps;not null" json:"full_win_fps"`
	FullWinFpsCnt       int32     `gorm:"column:full_win_fps_cnt;not null" json:"full_win_fps_cnt"`
	FullWinNosyncFps    int32     `gorm:"column:full_win_nosync_fps;not null" json:"full_win_nosync_fps"`
	FullWinNosyncFpsCnt int32     `gorm:"column:full_win_nosync_fps_cnt;not null" json:"full_win_nosync_fps_cnt"`
}

// TableName DeadTowerLagIndexDaily's table name
func (*DeadTowerLagIndexDaily) TableName() string {
	return TableNameDeadTowerLagIndexDaily
}
