// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeathtowerTingLog = "deathtower_ting_log"

// DeathtowerTingLog mapped from table <deathtower_ting_log>
type DeathtowerTingLog struct {
	OccTime time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	Level   int32     `gorm:"column:level;primaryKey" json:"level"`
	TingCnt int32     `gorm:"column:ting_cnt;not null" json:"ting_cnt"`
}

// TableName DeathtowerTingLog's table name
func (*DeathtowerTingLog) TableName() string {
	return TableNameDeathtowerTingLog
}
