// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDirectxVersion = "directx_version"

// DirectxVersion mapped from table <directx_version>
type DirectxVersion struct {
	OccTime     time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerGroup int32     `gorm:"column:server_group;primaryKey" json:"server_group"`
	VerEtc      int32     `gorm:"column:ver_etc;not null" json:"ver_etc"`
	Ver8X       int32     `gorm:"column:ver_8_x;not null" json:"ver_8_x"`
	Ver90       int32     `gorm:"column:ver_9_0;not null" json:"ver_9_0"`
	Ver90A      int32     `gorm:"column:ver_9_0_a;not null" json:"ver_9_0_a"`
	Ver90B      int32     `gorm:"column:ver_9_0_b;not null" json:"ver_9_0_b"`
	Ver90C      int32     `gorm:"column:ver_9_0_c;not null" json:"ver_9_0_c"`
	Ver10X      int32     `gorm:"column:ver_10_x;not null" json:"ver_10_x"`
	Ver11X      int32     `gorm:"column:ver_11_x;not null" json:"ver_11_x"`
}

// TableName DirectxVersion's table name
func (*DirectxVersion) TableName() string {
	return TableNameDirectxVersion
}
