// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLagStatModule = "lag_stat_module"

// LagStatModule mapped from table <lag_stat_module>
type LagStatModule struct {
	OccTime   time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerID  int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	Module    int32     `gorm:"column:module;primaryKey" json:"module"`
	Average   int32     `gorm:"column:average;not null" json:"average"`
	Deviation int32     `gorm:"column:deviation;not null" json:"deviation"`
	Count_    int32     `gorm:"column:count;not null" json:"count"`
}

// TableName LagStatModule's table name
func (*LagStatModule) TableName() string {
	return TableNameLagStatModule
}
