// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLagStatDungeon = "lag_stat_dungeon"

// LagStatDungeon mapped from table <lag_stat_dungeon>
type LagStatDungeon struct {
	OccTime        time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerID       int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	DungeonIdx     int32     `gorm:"column:dungeon_idx;primaryKey" json:"dungeon_idx"`
	FirstAverage   int32     `gorm:"column:first_average;not null" json:"first_average"`
	FirstDeviation int32     `gorm:"column:first_deviation;not null" json:"first_deviation"`
	FirstCount     int32     `gorm:"column:first_count;not null" json:"first_count"`
	BossAverage    int32     `gorm:"column:boss_average;not null" json:"boss_average"`
	BossDeviation  int32     `gorm:"column:boss_deviation;not null" json:"boss_deviation"`
	BossCount      int32     `gorm:"column:boss_count;not null" json:"boss_count"`
}

// TableName LagStatDungeon's table name
func (*LagStatDungeon) TableName() string {
	return TableNameLagStatDungeon
}
