// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogLauncherStat = "log_launcher_stat"

// LogLauncherStat mapped from table <log_launcher_stat>
type LogLauncherStat struct {
	OccDate      time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	Execute      int32     `gorm:"column:execute;not null" json:"execute"`
	Cancel       int32     `gorm:"column:cancel;not null" json:"cancel"`
	Success      int32     `gorm:"column:success;not null" json:"success"`
	FirstSuccess int32     `gorm:"column:first_success;not null" json:"first_success"`
	P2p          float64   `gorm:"column:p2p;not null" json:"p2p"`
	AllTime      int64     `gorm:"column:all_time;not null" json:"all_time"`
	P2pCount     int32     `gorm:"column:p2p_count;not null" json:"p2p_count"`
	AllTimeCount int32     `gorm:"column:all_time_count;not null" json:"all_time_count"`
}

// TableName LogLauncherStat's table name
func (*LogLauncherStat) TableName() string {
	return TableNameLogLauncherStat
}
