// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMonitoringSpec = "monitoring_spec"

// MonitoringSpec mapped from table <monitoring_spec>
type MonitoringSpec struct {
	UniqueID            int32     `gorm:"column:unique_id;primaryKey;autoIncrement:true" json:"unique_id"`
	ModifyTime          time.Time `gorm:"column:modify_time" json:"modify_time"`
	SpecID              int32     `gorm:"column:spec_id" json:"spec_id"`
	CPUVendor           int32     `gorm:"column:cpu_vendor;not null" json:"cpu_vendor"`
	CPUProcessorNum     int32     `gorm:"column:cpu_processor_num;not null" json:"cpu_processor_num"`
	AboveCPUClock       int32     `gorm:"column:above_cpu_clock;not null" json:"above_cpu_clock"`
	BelowCPUClock       int32     `gorm:"column:below_cpu_clock;not null" json:"below_cpu_clock"`
	RAM                 int32     `gorm:"column:ram;not null" json:"ram"`
	VideocardVendor     int32     `gorm:"column:videocard_vendor;not null" json:"videocard_vendor"`
	VideocardDevice     int32     `gorm:"column:videocard_device;not null" json:"videocard_device"`
	VideocardTextureMem int32     `gorm:"column:videocard_texture_mem;not null" json:"videocard_texture_mem"`
	OsVersion           int32     `gorm:"column:os_version;not null" json:"os_version"`
}

// TableName MonitoringSpec's table name
func (*MonitoringSpec) TableName() string {
	return TableNameMonitoringSpec
}
