// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameP2pStatistic = "p2p_statistics"

// P2pStatistic mapped from table <p2p_statistics>
type P2pStatistic struct {
	OccTime          time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerGroup      int32     `gorm:"column:server_group;primaryKey" json:"server_group"`
	P2pUser          int32     `gorm:"column:p2p_user" json:"p2p_user"`
	P2pMinPing       int32     `gorm:"column:p2p_min_ping" json:"p2p_min_ping"`
	P2pMaxPing       int32     `gorm:"column:p2p_max_ping" json:"p2p_max_ping"`
	P2pAvgPing       int32     `gorm:"column:p2p_avg_ping" json:"p2p_avg_ping"`
	P2pOverPing100   int32     `gorm:"column:p2p_over_ping_100" json:"p2p_over_ping_100"`
	P2pOverPing200   int32     `gorm:"column:p2p_over_ping_200" json:"p2p_over_ping_200"`
	P2pOverPing300   int32     `gorm:"column:p2p_over_ping_300" json:"p2p_over_ping_300"`
	P2pOverPing400   int32     `gorm:"column:p2p_over_ping_400" json:"p2p_over_ping_400"`
	RelayUser        int32     `gorm:"column:relay_user" json:"relay_user"`
	RelayMinPing     int32     `gorm:"column:relay_min_ping" json:"relay_min_ping"`
	RelayMaxPing     int32     `gorm:"column:relay_max_ping" json:"relay_max_ping"`
	RelayAvgPing     int32     `gorm:"column:relay_avg_ping" json:"relay_avg_ping"`
	RelayOverPing100 int32     `gorm:"column:relay_over_ping_100" json:"relay_over_ping_100"`
	RelayOverPing200 int32     `gorm:"column:relay_over_ping_200" json:"relay_over_ping_200"`
	RelayOverPing300 int32     `gorm:"column:relay_over_ping_300" json:"relay_over_ping_300"`
	RelayOverPing400 int32     `gorm:"column:relay_over_ping_400" json:"relay_over_ping_400"`
}

// TableName P2pStatistic's table name
func (*P2pStatistic) TableName() string {
	return TableNameP2pStatistic
}
