// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameP2pConnectSuccessRate = "p2p_connect_success_rate"

// P2pConnectSuccessRate 대만 P2P 홀펀칭 성공&실패 여결 타입과 IP까지 함께남기는 작업
type P2pConnectSuccessRate struct {
	No            int32     `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	ServerGroup   int32     `gorm:"column:server_group;not null" json:"server_group"`
	ConnectedType int32     `gorm:"column:connected_type;not null" json:"connected_type"`
	RequiredTime  int32     `gorm:"column:required_time;not null" json:"required_time"`
	CheckTime     int32     `gorm:"column:check_time;not null" json:"check_time"`
	NationCode    string    `gorm:"column:nation_code;not null" json:"nation_code"`
	PeerAddress   string    `gorm:"column:peer_address;not null" json:"peer_address"`
	OccDate       time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
}

// TableName P2pConnectSuccessRate's table name
func (*P2pConnectSuccessRate) TableName() string {
	return TableNameP2pConnectSuccessRate
}
