// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameP2pnetworkStatistic = "p2pnetwork_statistic"

// P2pnetworkStatistic mapped from table <p2pnetwork_statistic>
type P2pnetworkStatistic struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OccTime             time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	ServerGroup         int32     `gorm:"column:server_group;not null" json:"server_group"`
	SuccessPartyTry     int32     `gorm:"column:success_party_try;not null" json:"success_party_try"`
	TotalPartyTry       int32     `gorm:"column:total_party_try;not null" json:"total_party_try"`
	DungeonBadPing      int32     `gorm:"column:dungeon_bad_ping;not null" json:"dungeon_bad_ping"`
	DungeonTotal        int32     `gorm:"column:dungeon_total;not null" json:"dungeon_total"`
	PvpBadPing          int32     `gorm:"column:pvp_bad_ping;not null" json:"pvp_bad_ping"`
	PvpTotal            int32     `gorm:"column:pvp_total;not null" json:"pvp_total"`
	SuccessDungeonClear int32     `gorm:"column:success_dungeon_clear;not null" json:"success_dungeon_clear"`
	TotalDungeonClear   int32     `gorm:"column:total_dungeon_clear;not null" json:"total_dungeon_clear"`
	FairPvpTotal        int32     `gorm:"column:fair_pvp_total" json:"fair_pvp_total"`
	FairPvpBadPing      int32     `gorm:"column:fair_pvp_bad_ping" json:"fair_pvp_bad_ping"`
}

// TableName P2pnetworkStatistic's table name
func (*P2pnetworkStatistic) TableName() string {
	return TableNameP2pnetworkStatistic
}
