// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePacketOverflow = "packet_overflow"

// PacketOverflow mapped from table <packet_overflow>
type PacketOverflow struct {
	PacketType int32  `gorm:"column:packet_type;primaryKey" json:"packet_type"`
	PacketKind string `gorm:"column:packet_kind;primaryKey" json:"packet_kind"`
	Cnt        int32  `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName PacketOverflow's table name
func (*PacketOverflow) TableName() string {
	return TableNamePacketOverflow
}
