// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePowerwarTingType = "powerwar_ting_type"

// PowerwarTingType mapped from table <powerwar_ting_type>
type PowerwarTingType struct {
	OccTime  time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerID int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	TingType int32     `gorm:"column:ting_type;primaryKey" json:"ting_type"`
	TingCnt  int32     `gorm:"column:ting_cnt;not null" json:"ting_cnt"`
}

// TableName PowerwarTingType's table name
func (*PowerwarTingType) TableName() string {
	return TableNamePowerwarTingType
}
