// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTechnicalCategory = "technical_category"

// TechnicalCategory mapped from table <technical_category>
type TechnicalCategory struct {
	Cateno  int32  `gorm:"column:cateno;not null" json:"cateno"`
	Pcateno int32  `gorm:"column:pcateno;not null" json:"pcateno"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Step    int32  `gorm:"column:step;not null" json:"step"`
}

// TableName TechnicalCategory's table name
func (*TechnicalCategory) TableName() string {
	return TableNameTechnicalCategory
}
