// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTingUserAccount = "ting_user_account"

// TingUserAccount mapped from table <ting_user_account>
type TingUserAccount struct {
	OccTime time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	MID     int32     `gorm:"column:m_id;not null" json:"m_id"`
	Minute  int32     `gorm:"column:minute;not null" json:"minute"`
}

// TableName TingUserAccount's table name
func (*TingUserAccount) TableName() string {
	return TableNameTingUserAccount
}
