// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsedMemory = "used_memory"

// UsedMemory mapped from table <used_memory>
type UsedMemory struct {
	OccTime    time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	MinuteType string    `gorm:"column:minute_type;primaryKey;default:0" json:"minute_type"`
	Module     string    `gorm:"column:module;primaryKey;default:0" json:"module"`
	Memory     int32     `gorm:"column:memory;not null" json:"memory"`
}

// TableName UsedMemory's table name
func (*UsedMemory) TableName() string {
	return TableNameUsedMemory
}
