// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildBb = "guild_bbs"

// GuildBb mapped from table <guild_bbs>
type GuildBb struct {
	Gno      int32  `gorm:"column:gno;primaryKey;autoIncrement:true" json:"gno"`
	BdID     int32  `gorm:"column:bd_id;not null" json:"bd_id"`
	Empyn    int32  `gorm:"column:empyn;not null" json:"empyn"`
	Mgno     int32  `gorm:"column:mgno;not null" json:"mgno"`
	Open     bool   `gorm:"column:open;not null;default:1" json:"open"`
	Main     int32  `gorm:"column:main;not null" json:"main"`
	RegDate  int32  `gorm:"column:reg_date;not null" json:"reg_date"`
	ModDate  int32  `gorm:"column:mod_date;not null" json:"mod_date"`
	Hits     int32  `gorm:"column:hits;not null" json:"hits"`
	BodyType string `gorm:"column:body_type;not null" json:"body_type"`
	MID      int32  `gorm:"column:m_id;not null" json:"m_id"`
	RegID    string `gorm:"column:reg_id;not null" json:"reg_id"`
	Subject  string `gorm:"column:subject;not null" json:"subject"`
}

// TableName GuildBb's table name
func (*GuildBb) TableName() string {
	return TableNameGuildBb
}
