// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildInfo = "guild_info"

// GuildInfo mapped from table <guild_info>
type GuildInfo struct {
	GuildID          int32     `gorm:"column:guild_id;primaryKey;autoIncrement:true" json:"guild_id"`
	ServerID         int32     `gorm:"column:server_id;not null" json:"server_id"`
	GuildName        string    `gorm:"column:guild_name;not null" json:"guild_name"`
	MasterID         int32     `gorm:"column:master_id;not null" json:"master_id"`
	MasterNo         int32     `gorm:"column:master_no;not null" json:"master_no"`
	MasterName       string    `gorm:"column:master_name;not null" json:"master_name"`
	GuildURL         string    `gorm:"column:guild_url;not null" json:"guild_url"`
	GuildIcon        int32     `gorm:"column:guild_icon;not null" json:"guild_icon"`
	CreateTime       time.Time `gorm:"column:create_time;not null" json:"create_time"`
	Lev              int32     `gorm:"column:lev;not null" json:"lev"`
	Ability          int32     `gorm:"column:ability;not null" json:"ability"`
	ExpireFlag       int32     `gorm:"column:expire_flag;not null" json:"expire_flag"`
	ExpireTime       time.Time `gorm:"column:expire_time;not null" json:"expire_time"`
	MemberSecedeTime time.Time `gorm:"column:member_secede_time;not null" json:"member_secede_time"`
	MemberCount      int32     `gorm:"column:member_count;not null" json:"member_count"`
	RecommendFlag    int32     `gorm:"column:recommend_flag;not null" json:"recommend_flag"`
	RecommendTime    time.Time `gorm:"column:recommend_time;not null" json:"recommend_time"`
	GuildPoint       int32     `gorm:"column:guild_point;not null" json:"guild_point"`
	GuildPointAcc    int32     `gorm:"column:guild_point_acc;not null" json:"guild_point_acc"`
	GuildPointPrev   int32     `gorm:"column:guild_point_prev;not null" json:"guild_point_prev"`
	GuildRank        int32     `gorm:"column:guild_rank;not null" json:"guild_rank"`
	GuildWarPoint    int32     `gorm:"column:guild_war_point;not null" json:"guild_war_point"`
	FinalEntry       int32     `gorm:"column:final_entry;not null" json:"final_entry"`
	FinalWin         int32     `gorm:"column:final_win;not null" json:"final_win"`
	GuildIconAuth    int32     `gorm:"column:guild_icon_auth;not null" json:"guild_icon_auth"`
	GuildExp         int32     `gorm:"column:guild_exp;not null" json:"guild_exp"`
	PowerSide        int32     `gorm:"column:power_side;not null" json:"power_side"`
	GuildAgitFlag    int32     `gorm:"column:guild_agit_flag;not null" json:"guild_agit_flag"`
	LevUpTime        time.Time `gorm:"column:lev_up_time;not null" json:"lev_up_time"`
	PowerSecedeTime  time.Time `gorm:"column:power_secede_time;not null" json:"power_secede_time"`
	PowerWarPoint    int32     `gorm:"column:power_war_point;not null" json:"power_war_point"`
	PowerJoinCount   int32     `gorm:"column:power_join_count;not null" json:"power_join_count"`
	GuildFund        int32     `gorm:"column:guild_fund;not null" json:"guild_fund"`
}

// TableName GuildInfo's table name
func (*GuildInfo) TableName() string {
	return TableNameGuildInfo
}
