// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildStatUv = "guild_stat_uv"

// GuildStatUv mapped from table <guild_stat_uv>
type GuildStatUv struct {
	OccDate      time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	Pv           int32     `gorm:"column:pv" json:"pv"`
	NewBbs       int32     `gorm:"column:new_bbs;not null" json:"new_bbs"`
	TotalReadBbs int32     `gorm:"column:total_read_bbs;not null" json:"total_read_bbs"`
	MemberUv     int32     `gorm:"column:member_uv;not null" json:"member_uv"`
	MemberUvWeek int32     `gorm:"column:member_uv_week;not null" json:"member_uv_week"`
	MasterUv     int32     `gorm:"column:master_uv;not null" json:"master_uv"`
	MasterUvWeek int32     `gorm:"column:master_uv_week;not null" json:"master_uv_week"`
}

// TableName GuildStatUv's table name
func (*GuildStatUv) TableName() string {
	return TableNameGuildStatUv
}
