// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildBody = "guild_body"

// GuildBody mapped from table <guild_body>
type GuildBody struct {
	Gno  int32  `gorm:"column:gno;primaryKey" json:"gno"`
	Body string `gorm:"column:body;not null" json:"body"`
}

// TableName GuildBody's table name
func (*GuildBody) TableName() string {
	return TableNameGuildBody
}
