// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildHalloffameHTML = "guild_halloffame_html"

// GuildHalloffameHTML mapped from table <guild_halloffame_html>
type GuildHalloffameHTML struct {
	FameID int32  `gorm:"column:fame_id;primaryKey" json:"fame_id"`
	Title  string `gorm:"column:title;not null" json:"title"`
	HTML   string `gorm:"column:html;not null" json:"html"`
}

// TableName GuildHalloffameHTML's table name
func (*GuildHalloffameHTML) TableName() string {
	return TableNameGuildHalloffameHTML
}
