// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildSearch = "guild_search"

// GuildSearch mapped from table <guild_search>
type GuildSearch struct {
	GuildID       int32     `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	ServerID      int32     `gorm:"column:server_id;not null" json:"server_id"`
	GuildName     string    `gorm:"column:guild_name;not null" json:"guild_name"`
	MasterName    string    `gorm:"column:master_name;not null" json:"master_name"`
	CreateTime    time.Time `gorm:"column:create_time;not null" json:"create_time"`
	Lev           int32     `gorm:"column:lev;not null" json:"lev"`
	MemberCount   int32     `gorm:"column:member_count;not null" json:"member_count"`
	GuildPointAcc int32     `gorm:"column:guild_point_acc;not null" json:"guild_point_acc"`
	GuildExp      int32     `gorm:"column:guild_exp;not null" json:"guild_exp"`
	GuildURL      string    `gorm:"column:guild_url;not null" json:"guild_url"`
}

// TableName GuildSearch's table name
func (*GuildSearch) TableName() string {
	return TableNameGuildSearch
}
