// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildExpRef = "guild_exp_ref"

// GuildExpRef mapped from table <guild_exp_ref>
type GuildExpRef struct {
	Grade int32 `gorm:"column:grade;primaryKey" json:"grade"`
	Exp   int32 `gorm:"column:exp;not null" json:"exp"`
}

// TableName GuildExpRef's table name
func (*GuildExpRef) TableName() string {
	return TableNameGuildExpRef
}
