// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildGradeLog = "guild_grade_log"

// GuildGradeLog mapped from table <guild_grade_log>
type GuildGradeLog struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GuildID    int32     `gorm:"column:guild_id;not null" json:"guild_id"`
	MID        int32     `gorm:"column:m_id;not null" json:"m_id"`
	ServerID   int32     `gorm:"column:server_id;not null;default:1" json:"server_id"`
	CharacNo   int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	CharacName string    `gorm:"column:charac_name;not null" json:"charac_name"`
	OccTime    time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	GradePrev  int32     `gorm:"column:grade_prev;not null" json:"grade_prev"`
	GradeNext  int32     `gorm:"column:grade_next;not null" json:"grade_next"`
	Reason     string    `gorm:"column:reason;not null" json:"reason"`
	AdminNo    int32     `gorm:"column:admin_no" json:"admin_no"`
	AdminName  string    `gorm:"column:admin_name;not null" json:"admin_name"`
}

// TableName GuildGradeLog's table name
func (*GuildGradeLog) TableName() string {
	return TableNameGuildGradeLog
}
