// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildSkill = "guild_skill"

// GuildSkill mapped from table <guild_skill>
type GuildSkill struct {
	GuildID   int32  `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	RemainSp  int32  `gorm:"column:remain_sp;not null" json:"remain_sp"`
	SkillSlot []byte `gorm:"column:skill_slot;not null" json:"skill_slot"`
	UsedSp    int32  `gorm:"column:used_sp;not null" json:"used_sp"`
}

// TableName GuildSkill's table name
func (*GuildSkill) TableName() string {
	return TableNameGuildSkill
}
