// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePowerWarUserRank = "power_war_user_rank"

// PowerWarUserRank mapped from table <power_war_user_rank>
type PowerWarUserRank struct {
	ServerID      int32 `gorm:"column:server_id;primaryKey" json:"server_id"`
	Rank          int32 `gorm:"column:rank;not null" json:"rank"`
	CharacNo      int32 `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	PowerWarPoint int32 `gorm:"column:power_war_point;not null" json:"power_war_point"`
	PowerSide     int32 `gorm:"column:power_side;not null" json:"power_side"`
}

// TableName PowerWarUserRank's table name
func (*PowerWarUserRank) TableName() string {
	return TableNamePowerWarUserRank
}
