// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePowerWarGuildRank = "power_war_guild_rank"

// PowerWarGuildRank mapped from table <power_war_guild_rank>
type PowerWarGuildRank struct {
	ServerID      int32 `gorm:"column:server_id;not null" json:"server_id"`
	Rank          int32 `gorm:"column:rank;not null" json:"rank"`
	GuildID       int32 `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	PowerWarPoint int32 `gorm:"column:power_war_point;not null" json:"power_war_point"`
	PowerSide     int32 `gorm:"column:power_side;not null" json:"power_side"`
}

// TableName PowerWarGuildRank's table name
func (*PowerWarGuildRank) TableName() string {
	return TableNamePowerWarGuildRank
}
