// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePowerWarStatueRanker = "power_war_statue_ranker"

// PowerWarStatueRanker mapped from table <power_war_statue_ranker>
type PowerWarStatueRanker struct {
	ServerID     int32 `gorm:"column:server_id;primaryKey" json:"server_id"`
	FirstRanker  int32 `gorm:"column:first_ranker;not null" json:"first_ranker"`
	SecondRanker int32 `gorm:"column:second_ranker;not null" json:"second_ranker"`
	ThirdRanker  int32 `gorm:"column:third_ranker;not null" json:"third_ranker"`
}

// TableName PowerWarStatueRanker's table name
func (*PowerWarStatueRanker) TableName() string {
	return TableNamePowerWarStatueRanker
}
