// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountCerashopRestrict = "account_cerashop_restrict"

// AccountCerashopRestrict mapped from table <account_cerashop_restrict>
type AccountCerashopRestrict struct {
	MID            int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	IpgNo          int32 `gorm:"column:ipg_no;primaryKey" json:"ipg_no"`
	Count_         int32 `gorm:"column:count;not null" json:"count"`
	NextDate       int32 `gorm:"column:next_date;not null" json:"next_date"`
	EndDate        int32 `gorm:"column:end_date;not null" json:"end_date"`
	LastAccessDate int32 `gorm:"column:last_access_date;not null" json:"last_access_date"`
}

// TableName AccountCerashopRestrict's table name
func (*AccountCerashopRestrict) TableName() string {
	return TableNameAccountCerashopRestrict
}
