// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	UID         int32  `gorm:"column:UID;primaryKey;autoIncrement:true" json:"UID"`
	Accountname string `gorm:"column:accountname;not null" json:"accountname"`
	Password    string `gorm:"column:password;not null" json:"password"`
	VIP         int32  `gorm:"column:VIP;default:0" json:"VIP"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
