// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminMember = "admin_member"

// AdminMember mapped from table <admin_member>
type AdminMember struct {
	No          int32  `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	UserID      string `gorm:"column:user_id;not null" json:"user_id"`
	Password    string `gorm:"column:password;not null" json:"password"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Email       string `gorm:"column:email" json:"email"`
	Phone       string `gorm:"column:phone" json:"phone"`
	Msn         string `gorm:"column:msn" json:"msn"`
	Comment     string `gorm:"column:comment" json:"comment"`
	RegDate     int32  `gorm:"column:reg_date" json:"reg_date"`
	Confirm     string `gorm:"column:confirm" json:"confirm"`
	Level       string `gorm:"column:level;not null" json:"level"`
	LevelGroup1 string `gorm:"column:level_group1;not null;default:_" json:"level_group1"`
	LevelGroup2 string `gorm:"column:level_group2;not null;default:_" json:"level_group2"`
	LevelGroup3 string `gorm:"column:level_group3;not null;default:_" json:"level_group3"`
	LevelGroup4 string `gorm:"column:level_group4;not null;default:_" json:"level_group4"`
	LevelGroup5 string `gorm:"column:level_group5;not null;default:_" json:"level_group5"`
	LevelGroup6 string `gorm:"column:level_group6;not null;default:_" json:"level_group6"`
}

// TableName AdminMember's table name
func (*AdminMember) TableName() string {
	return TableNameAdminMember
}
