// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBadUser = "bad_user"

// BadUser mapped from table <bad_user>
type BadUser struct {
	No        int32 `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	MID       int32 `gorm:"column:m_id;not null" json:"m_id"`
	BadCode   int32 `gorm:"column:bad_code;not null" json:"bad_code"`
	CreateDay int32 `gorm:"column:create_day;not null" json:"create_day"`
	ExitDay   int32 `gorm:"column:exit_day;not null" json:"exit_day"`
	AdminN    int32 `gorm:"column:admin_n;not null" json:"admin_n"`
}

// TableName BadUser's table name
func (*BadUser) TableName() string {
	return TableNameBadUser
}
