// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBakDnfItemInfo = "bak_dnf_item_info"

// BakDnfItemInfo mapped from table <bak_dnf_item_info>
type BakDnfItemInfo struct {
	ItNo                 int32   `gorm:"column:it_no;primaryKey" json:"it_no"`
	ItName               string  `gorm:"column:it_name;not null" json:"it_name"`
	ItEngName            string  `gorm:"column:it_eng_name;not null" json:"it_eng_name"`
	ItExplain            string  `gorm:"column:it_explain;not null" json:"it_explain"`
	MasterType           int32   `gorm:"column:master_type;not null" json:"master_type"`
	SubType              int32   `gorm:"column:sub_type;not null" json:"sub_type"`
	Job                  string  `gorm:"column:job;not null" json:"job"`
	Class                int32   `gorm:"column:class;not null" json:"class"`
	Revert               string  `gorm:"column:revert;not null" json:"revert"`
	Level                int32   `gorm:"column:level;not null" json:"level"`
	Skill                int32   `gorm:"column:skill;not null" json:"skill"`
	CreateRatio          float32 `gorm:"column:create_ratio;not null" json:"create_ratio"`
	Rarity               int32   `gorm:"column:rarity;not null" json:"rarity"`
	Weight               int32   `gorm:"column:weight;not null" json:"weight"`
	Price                int32   `gorm:"column:price;not null" json:"price"`
	Cash                 int32   `gorm:"column:cash;not null" json:"cash"`
	Medal                int32   `gorm:"column:medal;not null" json:"medal"`
	Durability           int32   `gorm:"column:durability;not null" json:"durability"`
	Cooltime             int32   `gorm:"column:cooltime;not null" json:"cooltime"`
	HpMax                int32   `gorm:"column:hp_max;not null" json:"hp_max"`
	MpMax                int32   `gorm:"column:mp_max;not null" json:"mp_max"`
	PhyAtt               int32   `gorm:"column:phy_att;not null" json:"phy_att"`
	PhyDef               int32   `gorm:"column:phy_def;not null" json:"phy_def"`
	MagAtt               int32   `gorm:"column:mag_att;not null" json:"mag_att"`
	MagDef               int32   `gorm:"column:mag_def;not null" json:"mag_def"`
	EquipPhyAtt          int32   `gorm:"column:equip_phy_att;not null" json:"equip_phy_att"`
	EquipPhyDef          int32   `gorm:"column:equip_phy_def;not null" json:"equip_phy_def"`
	EquipMagAtt          int32   `gorm:"column:equip_mag_att;not null" json:"equip_mag_att"`
	EquipMagDef          int32   `gorm:"column:equip_mag_def;not null" json:"equip_mag_def"`
	RefFire              int32   `gorm:"column:ref_fire;not null" json:"ref_fire"`
	RefWater             int32   `gorm:"column:ref_water;not null" json:"ref_water"`
	RefDark              int32   `gorm:"column:ref_dark;not null" json:"ref_dark"`
	RefLight             int32   `gorm:"column:ref_light;not null" json:"ref_light"`
	RefAll               int32   `gorm:"column:ref_all;not null" json:"ref_all"`
	RefSlow              int32   `gorm:"column:ref_slow;not null" json:"ref_slow"`
	RefFreeze            int32   `gorm:"column:ref_freeze;not null" json:"ref_freeze"`
	RefPoison            int32   `gorm:"column:ref_poison;not null" json:"ref_poison"`
	RefStun              int32   `gorm:"column:ref_stun;not null" json:"ref_stun"`
	RefCus               int32   `gorm:"column:ref_cus;not null" json:"ref_cus"`
	RefBlind             int32   `gorm:"column:ref_blind;not null" json:"ref_blind"`
	RefLite              int32   `gorm:"column:ref_lite;not null" json:"ref_lite"`
	RefSton              int32   `gorm:"column:ref_ston;not null" json:"ref_ston"`
	RefSleep             int32   `gorm:"column:ref_sleep;not null" json:"ref_sleep"`
	RefDeekement         int32   `gorm:"column:ref_deekement;not null" json:"ref_deekement"`
	RefDeadlystrike      int32   `gorm:"column:ref_deadlystrike;not null" json:"ref_deadlystrike"`
	RefBleeding          int32   `gorm:"column:ref_bleeding;not null" json:"ref_bleeding"`
	RefConfuse           int32   `gorm:"column:ref_confuse;not null" json:"ref_confuse"`
	RefHold              int32   `gorm:"column:ref_hold;not null" json:"ref_hold"`
	RefAllStat           int32   `gorm:"column:ref_all_stat;not null" json:"ref_all_stat"`
	RefPierce            int32   `gorm:"column:ref_pierce;not null" json:"ref_pierce"`
	RefStuck             int32   `gorm:"column:ref_stuck;not null" json:"ref_stuck"`
	InvenMax             int32   `gorm:"column:inven_max;not null" json:"inven_max"`
	HpRegenrate          int32   `gorm:"column:hp_regenrate;not null" json:"hp_regenrate"`
	MpRegenrate          int32   `gorm:"column:mp_regenrate;not null" json:"mp_regenrate"`
	MovSpeed             int32   `gorm:"column:mov_speed;not null" json:"mov_speed"`
	AttSpeed             int32   `gorm:"column:att_speed;not null" json:"att_speed"`
	Quest                int32   `gorm:"column:quest;not null" json:"quest"`
	HitRecovery          int32   `gorm:"column:hit_recovery;not null" json:"hit_recovery"`
	Jump                 int32   `gorm:"column:jump;not null" json:"jump"`
	AttElement           string  `gorm:"column:att_element;not null;default:Void" json:"att_element"`
	AttActiveStatus      int32   `gorm:"column:att_active_status;not null" json:"att_active_status"`
	AttActiveStatusRatio float32 `gorm:"column:att_active_status_ratio;not null" json:"att_active_status_ratio"`
	AttActiveStatusPow   int32   `gorm:"column:att_active_status_pow;not null" json:"att_active_status_pow"`
	AttBackforce         int32   `gorm:"column:att_backforce;not null" json:"att_backforce"`
	AttUpforce           int32   `gorm:"column:att_upforce;not null" json:"att_upforce"`
	AttHpDrain           int32   `gorm:"column:att_hp_drain;not null" json:"att_hp_drain"`
	AttMpDrain           int32   `gorm:"column:att_mp_drain;not null" json:"att_mp_drain"`
	CriticalhitRate      float32 `gorm:"column:criticalhit_rate;not null" json:"criticalhit_rate"`
	StuckRate            float32 `gorm:"column:stuck_rate;not null" json:"stuck_rate"`
	AttDefenseIgnore     int32   `gorm:"column:att_defenseIgnore;not null" json:"att_defenseIgnore"`
	SkillLevelup         string  `gorm:"column:skill_levelup;not null" json:"skill_levelup"`
	SetType              string  `gorm:"column:set_type;not null;default:n" json:"set_type"`
	URL                  string  `gorm:"column:url;not null" json:"url"`
	JewelType            string  `gorm:"column:jewel_type;not null" json:"jewel_type"`
}

// TableName BakDnfItemInfo's table name
func (*BakDnfItemInfo) TableName() string {
	return TableNameBakDnfItemInfo
}
