// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChStatus = "ch_status"

// ChStatus mapped from table <ch_status>
type ChStatus struct {
	GcGroup  int32 `gorm:"column:gc_group;not null;default:1" json:"gc_group"`
	GcStatus int32 `gorm:"column:gc_status;not null" json:"gc_status"`
}

// TableName ChStatus's table name
func (*ChStatus) TableName() string {
	return TableNameChStatus
}
