// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCheckPickUpRandomOptionItem = "check_pick_up_random_option_item"

// CheckPickUpRandomOptionItem mapped from table <check_pick_up_random_option_item>
type CheckPickUpRandomOptionItem struct {
	MID        int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	CheckCount int32 `gorm:"column:check_count;not null" json:"check_count"`
}

// TableName CheckPickUpRandomOptionItem's table name
func (*CheckPickUpRandomOptionItem) TableName() string {
	return TableNameCheckPickUpRandomOptionItem
}
