// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDbConnect = "db_connect"

// DbConnect mapped from table <db_connect>
type DbConnect struct {
	No            int32  `gorm:"column:no;not null" json:"no"`
	HostName      string `gorm:"column:host_name" json:"host_name"`
	DbServerGroup int32  `gorm:"column:db_server_group" json:"db_server_group"`
	DbType        int32  `gorm:"column:db_type;not null" json:"db_type"`
	DbName        string `gorm:"column:db_name;not null" json:"db_name"`
	DbIP          string `gorm:"column:db_ip;not null" json:"db_ip"`
	DbPort        int32  `gorm:"column:db_port;not null" json:"db_port"`
	DbUserid      string `gorm:"column:db_userid;not null" json:"db_userid"`
	DbPasswd      string `gorm:"column:db_passwd;not null" json:"db_passwd"`
	Comments      string `gorm:"column:comments" json:"comments"`
}

// TableName DbConnect's table name
func (*DbConnect) TableName() string {
	return TableNameDbConnect
}
