// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfStory = "dnf_story"

// DnfStory mapped from table <dnf_story>
type DnfStory struct {
	No          int32     `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	StoryType   int32     `gorm:"column:story_type;not null" json:"story_type"`
	NoticeFlag  int32     `gorm:"column:notice_flag;not null" json:"notice_flag"`
	MID         int32     `gorm:"column:m_id;not null" json:"m_id"`
	RegID       string    `gorm:"column:reg_id;not null" json:"reg_id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	URL         string    `gorm:"column:url;not null" json:"url"`
	ImgName     string    `gorm:"column:img_name;not null" json:"img_name"`
	Opt         int32     `gorm:"column:opt;not null" json:"opt"`
	OpenFlag    string    `gorm:"column:open_flag;not null;default:n" json:"open_flag"`
	RegDate     time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
	Hits        int32     `gorm:"column:hits;not null" json:"hits"`
	ReserveTime int32     `gorm:"column:reserve_time;not null" json:"reserve_time"`
	Content     string    `gorm:"column:content" json:"content"`
}

// TableName DnfStory's table name
func (*DnfStory) TableName() string {
	return TableNameDnfStory
}
