// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfEventAddress = "dnf_event_address"

// DnfEventAddress mapped from table <dnf_event_address>
type DnfEventAddress struct {
	EventID int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	MID     int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccDate time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
	Zipcode string    `gorm:"column:zipcode;not null" json:"zipcode"`
	Address string    `gorm:"column:address;not null" json:"address"`
	PhoneNo string    `gorm:"column:phone_no;not null" json:"phone_no"`
}

// TableName DnfEventAddress's table name
func (*DnfEventAddress) TableName() string {
	return TableNameDnfEventAddress
}
