// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDnfEventLog = "dnf_event_log"

// DnfEventLog mapped from table <dnf_event_log>
type DnfEventLog struct {
	LogID      int32  `gorm:"column:log_id;primaryKey;autoIncrement:true" json:"log_id"`
	OccTime    int32  `gorm:"column:occ_time;not null" json:"occ_time"`
	EventType  int32  `gorm:"column:event_type;not null" json:"event_type"`
	Parameter1 int32  `gorm:"column:parameter1;not null" json:"parameter1"`
	Parameter2 int32  `gorm:"column:parameter2;not null" json:"parameter2"`
	ServerID   int32  `gorm:"column:server_id;not null" json:"server_id"`
	EventFlag  int32  `gorm:"column:event_flag" json:"event_flag"`
	StartTime  int32  `gorm:"column:start_time;not null" json:"start_time"`
	EndTime    int32  `gorm:"column:end_time;not null" json:"end_time"`
	MID        int32  `gorm:"column:m_id;not null" json:"m_id"`
	Expl       string `gorm:"column:expl;not null" json:"expl"`
	Etc        string `gorm:"column:etc;not null" json:"etc"`
}

// TableName DnfEventLog's table name
func (*DnfEventLog) TableName() string {
	return TableNameDnfEventLog
}
