// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfEventInfo = "dnf_event_info"

// DnfEventInfo mapped from table <dnf_event_info>
type DnfEventInfo struct {
	EventID      int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	EventName    string    `gorm:"column:event_name;not null" json:"event_name"`
	EventExplain string    `gorm:"column:event_explain;not null" json:"event_explain"`
	ApplyType    int32     `gorm:"column:apply_type;not null" json:"apply_type"`
	StartDate    time.Time `gorm:"column:start_date;not null" json:"start_date"`
	EndDate      time.Time `gorm:"column:end_date;not null" json:"end_date"`
}

// TableName DnfEventInfo's table name
func (*DnfEventInfo) TableName() string {
	return TableNameDnfEventInfo
}
