// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfGameinNotice = "dnf_gamein_notice"

// DnfGameinNotice mapped from table <dnf_gamein_notice>
type DnfGameinNotice struct {
	No       int32     `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	ImgName  string    `gorm:"column:img_name;not null" json:"img_name"`
	ServerID int32     `gorm:"column:server_id;not null" json:"server_id"`
	RegTime  time.Time `gorm:"column:reg_time;not null" json:"reg_time"`
	OpenFlag string    `gorm:"column:open_flag;default:n" json:"open_flag"`
}

// TableName DnfGameinNotice's table name
func (*DnfGameinNotice) TableName() string {
	return TableNameDnfGameinNotice
}
