// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfRestrictState = "dnf_restrict_state"

// DnfRestrictState mapped from table <dnf_restrict_state>
type DnfRestrictState struct {
	ServerGroup   int32     `gorm:"column:server_group;primaryKey" json:"server_group"`
	Category      int32     `gorm:"column:category;primaryKey" json:"category"`
	RestrictCode  int32     `gorm:"column:restrict_code;primaryKey" json:"restrict_code"`
	RestrictValue string    `gorm:"column:restrict_value;not null" json:"restrict_value"`
	ModDate       time.Time `gorm:"column:mod_date;not null" json:"mod_date"`
	RegDate       time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
}

// TableName DnfRestrictState's table name
func (*DnfRestrictState) TableName() string {
	return TableNameDnfRestrictState
}
