// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDnfTestrMID = "dnf_testr_m_id"

// DnfTestrMID mapped from table <dnf_testr_m_id>
type DnfTestrMID struct {
	MID int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	Sex int32 `gorm:"column:sex;not null" json:"sex"`
}

// TableName DnfTestrMID's table name
func (*DnfTestrMID) TableName() string {
	return TableNameDnfTestrMID
}
