// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfGameMessage = "dnf_game_message"

// DnfGameMessage mapped from table <dnf_game_message>
type DnfGameMessage struct {
	No          int32     `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	Message     string    `gorm:"column:message" json:"message"`
	DisplayType int32     `gorm:"column:display_type;not null;default:1" json:"display_type"`
	StartH      int32     `gorm:"column:start_h;not null" json:"start_h"`
	EndH        int32     `gorm:"column:end_h;not null" json:"end_h"`
	OccDate     time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
}

// TableName DnfGameMessage's table name
func (*DnfGameMessage) TableName() string {
	return TableNameDnfGameMessage
}
