// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDnfPcroom = "dnf_pcroom"

// DnfPcroom mapped from table <dnf_pcroom>
type DnfPcroom struct {
	IPNo      int32  `gorm:"column:ip_no;primaryKey;autoIncrement:true" json:"ip_no"`
	District  string `gorm:"column:district;not null" json:"district"`
	FirmName  string `gorm:"column:firm_name;not null" json:"firm_name"`
	Telephone string `gorm:"column:telephone;not null" json:"telephone"`
	Address   string `gorm:"column:address;not null" json:"address"`
	Leader    string `gorm:"column:leader;not null" json:"leader"`
	StartIP   string `gorm:"column:start_ip;not null" json:"start_ip"`
	EndIP     string `gorm:"column:end_ip;not null" json:"end_ip"`
}

// TableName DnfPcroom's table name
func (*DnfPcroom) TableName() string {
	return TableNameDnfPcroom
}
