// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfRestrictInfo = "dnf_restrict_info"

// DnfRestrictInfo 서비스 제재 정보 문자열
type DnfRestrictInfo struct {
	Category     int32     `gorm:"column:category;primaryKey" json:"category"`
	RestrictCode int32     `gorm:"column:restrict_code;primaryKey" json:"restrict_code"`
	RestrictStr  string    `gorm:"column:restrict_str;not null" json:"restrict_str"`
	RegDate      time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
}

// TableName DnfRestrictInfo's table name
func (*DnfRestrictInfo) TableName() string {
	return TableNameDnfRestrictInfo
}
