// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDnfEventEntryNotuse = "dnf_event_entry_notuse"

// DnfEventEntryNotuse mapped from table <dnf_event_entry_notuse>
type DnfEventEntryNotuse struct {
	EventID    int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccDate    time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
	ServerID   int32     `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo   int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	ObtainDate time.Time `gorm:"column:obtain_date;not null" json:"obtain_date"`
}

// TableName DnfEventEntryNotuse's table name
func (*DnfEventEntryNotuse) TableName() string {
	return TableNameDnfEventEntryNotuse
}
