// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventNewmember0709Entry = "event_newmember0709_entry"

// EventNewmember0709Entry mapped from table <event_newmember0709_entry>
type EventNewmember0709Entry struct {
	MID        int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccDate    int32 `gorm:"column:occ_date;not null" json:"occ_date"`
	ServerID   int32 `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo   int32 `gorm:"column:charac_no;not null" json:"charac_no"`
	Item1No    int32 `gorm:"column:item1_no;not null" json:"item1_no"`
	Item1Check int32 `gorm:"column:item1_check;not null" json:"item1_check"`
	Item2No    int32 `gorm:"column:item2_no;not null" json:"item2_no"`
	Item2Check int32 `gorm:"column:item2_check;not null" json:"item2_check"`
}

// TableName EventNewmember0709Entry's table name
func (*EventNewmember0709Entry) TableName() string {
	return TableNameEventNewmember0709Entry
}
