// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventGoldcardEntry2 = "event_goldcard_entry2"

// EventGoldcardEntry2 mapped from table <event_goldcard_entry2>
type EventGoldcardEntry2 struct {
	OccDate   int32 `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	MID       int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServerID  int32 `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo  int32 `gorm:"column:charac_no;not null" json:"charac_no"`
	ItemNo    int32 `gorm:"column:item_no;not null" json:"item_no"`
	ItemCheck int32 `gorm:"column:item_check;not null" json:"item_check"`
}

// TableName EventGoldcardEntry2's table name
func (*EventGoldcardEntry2) TableName() string {
	return TableNameEventGoldcardEntry2
}
