// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventPandoraEntry200905 = "event_pandora_entry_200905"

// EventPandoraEntry200905 mapped from table <event_pandora_entry_200905>
type EventPandoraEntry200905 struct {
	MID      int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccDate  time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	ServerID int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	CharacNo int32     `gorm:"column:charac_no;not null" json:"charac_no"`
}

// TableName EventPandoraEntry200905's table name
func (*EventPandoraEntry200905) TableName() string {
	return TableNameEventPandoraEntry200905
}
