// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventGoldcardEntry1 = "event_goldcard_entry1"

// EventGoldcardEntry1 mapped from table <event_goldcard_entry1>
type EventGoldcardEntry1 struct {
	OccDate int32 `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	MID     int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	ItemNo  int32 `gorm:"column:item_no;not null" json:"item_no"`
}

// TableName EventGoldcardEntry1's table name
func (*EventGoldcardEntry1) TableName() string {
	return TableNameEventGoldcardEntry1
}
