// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventWebmoneystampItem = "event_webmoneystamp_item"

// EventWebmoneystampItem mapped from table <event_webmoneystamp_item>
type EventWebmoneystampItem struct {
	MID       int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime   int32 `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	ServerID  int32 `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo  int32 `gorm:"column:charac_no;not null" json:"charac_no"`
	ItemNo    int32 `gorm:"column:item_no;not null" json:"item_no"`
	ItemCheck int32 `gorm:"column:item_check;not null" json:"item_check"`
}

// TableName EventWebmoneystampItem's table name
func (*EventWebmoneystampItem) TableName() string {
	return TableNameEventWebmoneystampItem
}
