// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventAradBirthday6th = "event_arad_birthday_6th"

// EventAradBirthday6th mapped from table <event_arad_birthday_6th>
type EventAradBirthday6th struct {
	Server int32 `gorm:"column:server;primaryKey" json:"server"`
	Point  int32 `gorm:"column:point;not null" json:"point"`
}

// TableName EventAradBirthday6th's table name
func (*EventAradBirthday6th) TableName() string {
	return TableNameEventAradBirthday6th
}
