// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventQuestPartyMemberWeb = "event_quest_party_member_web"

// EventQuestPartyMemberWeb mapped from table <event_quest_party_member_web>
type EventQuestPartyMemberWeb struct {
	MID          int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServerID     int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	CharacNo     int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	QuestNo      int32     `gorm:"column:quest_no;primaryKey" json:"quest_no"`
	OccTime      time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	SendCharacNo int32     `gorm:"column:send_charac_no;not null" json:"send_charac_no"`
}

// TableName EventQuestPartyMemberWeb's table name
func (*EventQuestPartyMemberWeb) TableName() string {
	return TableNameEventQuestPartyMemberWeb
}
