// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventMage2year = "event_mage_2years"

// EventMage2year mapped from table <event_mage_2years>
type EventMage2year struct {
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServerInfo int32     `gorm:"column:server_info;primaryKey" json:"server_info"`
	CharacNo   int32     `gorm:"column:charac_no;primaryKey;autoIncrement:true" json:"charac_no"`
	CharacName string    `gorm:"column:charac_name;not null" json:"charac_name"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
	DeleteTime time.Time `gorm:"column:delete_time;not null" json:"delete_time"`
	DeleteFlag int32     `gorm:"column:delete_flag;not null" json:"delete_flag"`
}

// TableName EventMage2year's table name
func (*EventMage2year) TableName() string {
	return TableNameEventMage2year
}
