// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventCharacMov1th = "event_charac_mov_1th"

// EventCharacMov1th mapped from table <event_charac_mov_1th>
type EventCharacMov1th struct {
	ID           int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MID          int32 `gorm:"column:m_id;not null" json:"m_id"`
	ServerID     int32 `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo     int32 `gorm:"column:charac_no;not null" json:"charac_no"`
	MoveServerID int32 `gorm:"column:move_server_id;not null" json:"move_server_id"`
	MoveCharacNo int32 `gorm:"column:move_charac_no;not null" json:"move_charac_no"`
	MoveCheck    int32 `gorm:"column:move_check;not null" json:"move_check"`
}

// TableName EventCharacMov1th's table name
func (*EventCharacMov1th) TableName() string {
	return TableNameEventCharacMov1th
}
