// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventHinamatsuriCnt = "event_hinamatsuri_cnt"

// EventHinamatsuriCnt mapped from table <event_hinamatsuri_cnt>
type EventHinamatsuriCnt struct {
	Cnt int32 `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName EventHinamatsuriCnt's table name
func (*EventHinamatsuriCnt) TableName() string {
	return TableNameEventHinamatsuriCnt
}
