// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventGoldcardCnt = "event_goldcard_cnt"

// EventGoldcardCnt mapped from table <event_goldcard_cnt>
type EventGoldcardCnt struct {
	ItemNo  int32     `gorm:"column:item_no;primaryKey" json:"item_no"`
	OccDate time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	Cnt     int32     `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName EventGoldcardCnt's table name
func (*EventGoldcardCnt) TableName() string {
	return TableNameEventGoldcardCnt
}
