// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventSkill2025Entry = "event_skill2025_entry"

// EventSkill2025Entry mapped from table <event_skill2025_entry>
type EventSkill2025Entry struct {
	MID      int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServerID int32     `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	OccTime  time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
}

// TableName EventSkill2025Entry's table name
func (*EventSkill2025Entry) TableName() string {
	return TableNameEventSkill2025Entry
}
