// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventAradlotto0809Entry = "event_aradlotto_0809_entry"

// EventAradlotto0809Entry mapped from table <event_aradlotto_0809_entry>
type EventAradlotto0809Entry struct {
	MID      int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccDate  int32  `gorm:"column:occ_date;not null" json:"occ_date"`
	LottoNum string `gorm:"column:lotto_num;not null" json:"lotto_num"`
}

// TableName EventAradlotto0809Entry's table name
func (*EventAradlotto0809Entry) TableName() string {
	return TableNameEventAradlotto0809Entry
}
