// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventCharacMov1thEntry = "event_charac_mov_1th_entry"

// EventCharacMov1thEntry mapped from table <event_charac_mov_1th_entry>
type EventCharacMov1thEntry struct {
	MID       int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime   int32 `gorm:"column:occ_time;not null" json:"occ_time"`
	ItNo      int32 `gorm:"column:it_no;not null" json:"it_no"`
	ItemCheck int32 `gorm:"column:item_check;not null" json:"item_check"`
}

// TableName EventCharacMov1thEntry's table name
func (*EventCharacMov1thEntry) TableName() string {
	return TableNameEventCharacMov1thEntry
}
