// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameChannel = "game_channel"

// GameChannel mapped from table <game_channel>
type GameChannel struct {
	GcNo          int32  `gorm:"column:gc_no;primaryKey;autoIncrement:true" json:"gc_no"`
	GcNow         int32  `gorm:"column:gc_now;not null" json:"gc_now"`
	GcIP          string `gorm:"column:gc_ip;not null" json:"gc_ip"`
	GcPort        int32  `gorm:"column:gc_port;not null" json:"gc_port"`
	GcMax         int32  `gorm:"column:gc_max;not null" json:"gc_max"`
	GcGame        int32  `gorm:"column:gc_game;not null" json:"gc_game"`
	GcChannel     string `gorm:"column:gc_channel;not null" json:"gc_channel"`
	GcChGroup     int32  `gorm:"column:gc_ch_group;not null" json:"gc_ch_group"`
	GcChanneltype string `gorm:"column:gc_channeltype;not null" json:"gc_channeltype"`
}

// TableName GameChannel's table name
func (*GameChannel) TableName() string {
	return TableNameGameChannel
}
