// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGeoReject = "geo_reject"

// GeoReject mapped from table <geo_reject>
type GeoReject struct {
	RejIP       string    `gorm:"column:rej_ip;primaryKey" json:"rej_ip"`
	RejCCode    string    `gorm:"column:rej_c_code;not null" json:"rej_c_code"`
	RejIPCount  int32     `gorm:"column:rej_ip_count;not null" json:"rej_ip_count"`
	RejLastDate time.Time `gorm:"column:rej_last_date;not null;default:CURRENT_TIMESTAMP" json:"rej_last_date"`
	RejChk      string    `gorm:"column:rej_chk;not null;default:N" json:"rej_chk"`
	RejSrc      string    `gorm:"column:rej_src;not null;default:w" json:"rej_src"`
}

// TableName GeoReject's table name
func (*GeoReject) TableName() string {
	return TableNameGeoReject
}
