// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGeoAllowCountry = "geo_allow_country"

// GeoAllowCountry mapped from table <geo_allow_country>
type GeoAllowCountry struct {
	ServerGroup int32     `gorm:"column:server_group;primaryKey" json:"server_group"`
	CountryCode string    `gorm:"column:country_code;primaryKey" json:"country_code"`
	RegDate     time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
}

// TableName GeoAllowCountry's table name
func (*GeoAllowCountry) TableName() string {
	return TableNameGeoAllowCountry
}
