// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGiftTicketEntry = "gift_ticket_entry"

// GiftTicketEntry mapped from table <gift_ticket_entry>
type GiftTicketEntry struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GiftNo     int32  `gorm:"column:gift_no;not null" json:"gift_no"`
	BuyerID    int32  `gorm:"column:buyer_id;not null" json:"buyer_id"`
	BuyerDate  int32  `gorm:"column:buyer_date;not null" json:"buyer_date"`
	BuyerCode  string `gorm:"column:buyer_code;not null" json:"buyer_code"`
	BuyerCheck int32  `gorm:"column:buyer_check;not null" json:"buyer_check"`
	OtherID    int32  `gorm:"column:other_id;not null" json:"other_id"`
	OtherDate  int32  `gorm:"column:other_date;not null" json:"other_date"`
	OtherCode  string `gorm:"column:other_code;not null" json:"other_code"`
	OtherCheck int32  `gorm:"column:other_check;not null" json:"other_check"`
	Message    string `gorm:"column:message;not null" json:"message"`
}

// TableName GiftTicketEntry's table name
func (*GiftTicketEntry) TableName() string {
	return TableNameGiftTicketEntry
}
