// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGmManifestNotuse = "gm_manifest_notuse"

// GmManifestNotuse mapped from table <gm_manifest_notuse>
type GmManifestNotuse struct {
	MID   int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	Level int32 `gorm:"column:level;not null" json:"level"`
}

// TableName GmManifestNotuse's table name
func (*GmManifestNotuse) TableName() string {
	return TableNameGmManifestNotuse
}
