// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildRecommend = "guild_recommend"

// GuildRecommend mapped from table <guild_recommend>
type GuildRecommend struct {
	No            int32     `gorm:"column:no;primaryKey" json:"no"`
	GuildID       int32     `gorm:"column:guild_id;not null" json:"guild_id"`
	ServerID      int32     `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo      int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	CharacName    string    `gorm:"column:charac_name;not null" json:"charac_name"`
	Comment       string    `gorm:"column:comment;not null" json:"comment"`
	RecommendTime time.Time `gorm:"column:recommend_time;not null" json:"recommend_time"`
}

// TableName GuildRecommend's table name
func (*GuildRecommend) TableName() string {
	return TableNameGuildRecommend
}
