// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildStat = "guild_stat"

// GuildStat mapped from table <guild_stat>
type GuildStat struct {
	OccDate      time.Time `gorm:"column:occ_date;primaryKey" json:"occ_date"`
	Lev          int32     `gorm:"column:lev;primaryKey" json:"lev"`
	ServerID     int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	CreateNo     int32     `gorm:"column:create_no;not null" json:"create_no"`
	AccCreateNo  int32     `gorm:"column:acc_create_no;not null" json:"acc_create_no"`
	MemberNo     int32     `gorm:"column:member_no;not null" json:"member_no"`
	AccMemberNo  int32     `gorm:"column:acc_member_no;not null" json:"acc_member_no"`
	AvgLev       float32   `gorm:"column:avg_lev;not null" json:"avg_lev"`
	AvgMasterLev float32   `gorm:"column:avg_master_lev;not null" json:"avg_master_lev"`
}

// TableName GuildStat's table name
func (*GuildStat) TableName() string {
	return TableNameGuildStat
}
