// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGuildMember = "guild_member"

// GuildMember mapped from table <guild_member>
type GuildMember struct {
	GuildID         int32     `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	MID             int32     `gorm:"column:m_id;not null" json:"m_id"`
	ServerID        int32     `gorm:"column:server_id;not null" json:"server_id"`
	CharacNo        int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	CharacName      string    `gorm:"column:charac_name;not null" json:"charac_name"`
	NickName        string    `gorm:"column:nick_name;not null" json:"nick_name"`
	Grade           int32     `gorm:"column:grade;not null" json:"grade"`
	Job             int32     `gorm:"column:job;not null" json:"job"`
	GrowType        int32     `gorm:"column:grow_type;not null" json:"grow_type"`
	Lev             int32     `gorm:"column:lev;not null" json:"lev"`
	Age             int32     `gorm:"column:age;not null" json:"age"`
	BornYear        string    `gorm:"column:born_year;not null" json:"born_year"`
	Sex             string    `gorm:"column:sex;not null" json:"sex"`
	ApplyTime       time.Time `gorm:"column:apply_time;not null" json:"apply_time"`
	MemberTime      time.Time `gorm:"column:member_time;not null" json:"member_time"`
	MemberFlag      int32     `gorm:"column:member_flag;not null" json:"member_flag"`
	BbsCnt          int32     `gorm:"column:bbs_cnt;not null" json:"bbs_cnt"`
	LastVisitTime   time.Time `gorm:"column:last_visit_time;not null" json:"last_visit_time"`
	SecedeType      int32     `gorm:"column:secede_type;not null" json:"secede_type"`
	SecedeTime      time.Time `gorm:"column:secede_time;not null" json:"secede_time"`
	MemberPoint     int32     `gorm:"column:member_point;not null" json:"member_point"`
	MemberPointPrev int32     `gorm:"column:member_point_prev;not null" json:"member_point_prev"`
	LastPlayTime    time.Time `gorm:"column:last_play_time;not null" json:"last_play_time"`
}

// TableName GuildMember's table name
func (*GuildMember) TableName() string {
	return TableNameGuildMember
}
