// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildIntroduce = "guild_introduce"

// GuildIntroduce mapped from table <guild_introduce>
type GuildIntroduce struct {
	GuildID   int32  `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	ServerID  int32  `gorm:"column:server_id;not null" json:"server_id"`
	Introduce string `gorm:"column:introduce;not null" json:"introduce"`
}

// TableName GuildIntroduce's table name
func (*GuildIntroduce) TableName() string {
	return TableNameGuildIntroduce
}
