// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildMemberIntroduce = "guild_member_introduce"

// GuildMemberIntroduce mapped from table <guild_member_introduce>
type GuildMemberIntroduce struct {
	GuildID   int32  `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	CharacNo  int32  `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	Introduce string `gorm:"column:introduce;not null" json:"introduce"`
}

// TableName GuildMemberIntroduce's table name
func (*GuildMemberIntroduce) TableName() string {
	return TableNameGuildMemberIntroduce
}
