// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGuildRank = "guild_rank"

// GuildRank mapped from table <guild_rank>
type GuildRank struct {
	ServerID       int32  `gorm:"column:server_id;primaryKey" json:"server_id"`
	GuildID        int32  `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	GuildName      string `gorm:"column:guild_name;not null;default:0" json:"guild_name"`
	GuildRank      int32  `gorm:"column:guild_Rank;not null" json:"guild_Rank"`
	GuildPoint     int32  `gorm:"column:guild_point;not null" json:"guild_point"`
	GuildAccPoint  int32  `gorm:"column:guild_acc_point;not null" json:"guild_acc_point"`
	GuildVisit     int32  `gorm:"column:guild_visit;not null" json:"guild_visit"`
	GuildAccVisit  int32  `gorm:"column:guild_acc_visit;not null" json:"guild_acc_visit"`
	GuildMember    int32  `gorm:"column:guild_member;not null" json:"guild_member"`
	GuildAccMember int32  `gorm:"column:guild_acc_member;not null" json:"guild_acc_member"`
	GuildAvgLev    int32  `gorm:"column:guild_avg_lev;not null" json:"guild_avg_lev"`
}

// TableName GuildRank's table name
func (*GuildRank) TableName() string {
	return TableNameGuildRank
}
