// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJwtBlacklist = "jwt_blacklists"

// JwtBlacklist mapped from table <jwt_blacklists>
type JwtBlacklist struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UpdatedBy string         `gorm:"column:updated_by;default:系统自动;comment:更新操作人" json:"updated_by"` // 更新操作人
	Jwt       string         `gorm:"column:jwt;comment:jwt" json:"jwt"`                              // jwt
}

// TableName JwtBlacklist's table name
func (*JwtBlacklist) TableName() string {
	return TableNameJwtBlacklist
}
