// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLimitCreateCharacter = "limit_create_character"

// LimitCreateCharacter mapped from table <limit_create_character>
type LimitCreateCharacter struct {
	MID            int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	Count_         int32     `gorm:"column:count;not null" json:"count"`
	LastAccessTime time.Time `gorm:"column:last_access_time;not null" json:"last_access_time"`
}

// TableName LimitCreateCharacter's table name
func (*LimitCreateCharacter) TableName() string {
	return TableNameLimitCreateCharacter
}
