// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLimitedShopManager = "limited_shop_manager"

// LimitedShopManager mapped from table <limited_shop_manager>
type LimitedShopManager struct {
	No                     int32  `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	OccTime                int32  `gorm:"column:occ_time;not null" json:"occ_time"`
	ServerID               int32  `gorm:"column:server_id;primaryKey" json:"server_id"`
	IpgNo                  int32  `gorm:"column:ipg_no;primaryKey" json:"ipg_no"`
	ItemNo                 int32  `gorm:"column:item_no;not null" json:"item_no"`
	ItemCnt                int32  `gorm:"column:item_cnt;not null" json:"item_cnt"`
	CeraPrice              int32  `gorm:"column:cera_price;not null" json:"cera_price"`
	GoldPrice              int32  `gorm:"column:gold_price;not null" json:"gold_price"`
	AvatarPeriodType       int32  `gorm:"column:avatar_period_type;not null;default:-1" json:"avatar_period_type"`
	TotalCnt               int32  `gorm:"column:total_cnt;not null" json:"total_cnt"`
	SellCnt                int32  `gorm:"column:sell_cnt;not null" json:"sell_cnt"`
	RestrictNo             int32  `gorm:"column:restrict_no;not null" json:"restrict_no"`
	StartTime              int32  `gorm:"column:start_time;not null" json:"start_time"`
	EndTime                int32  `gorm:"column:end_time;not null" json:"end_time"`
	RealEndTime            int32  `gorm:"column:real_end_time;not null" json:"real_end_time"`
	NpcIdx                 int32  `gorm:"column:npc_idx;not null" json:"npc_idx"`
	CondCharacJob          int32  `gorm:"column:cond_charac_job;not null" json:"cond_charac_job"`
	CondLevBegin           int32  `gorm:"column:cond_lev_begin;not null" json:"cond_lev_begin"`
	CondLevEnd             int32  `gorm:"column:cond_lev_end;not null" json:"cond_lev_end"`
	CondAccCreateTimeBegin int32  `gorm:"column:cond_acc_create_time_begin;not null" json:"cond_acc_create_time_begin"`
	CondAccCreateTimeEnd   int32  `gorm:"column:cond_acc_create_time_end;not null" json:"cond_acc_create_time_end"`
	CondChaCreateTimeBegin int32  `gorm:"column:cond_cha_create_time_begin;not null" json:"cond_cha_create_time_begin"`
	CondChaCreateTimeEnd   int32  `gorm:"column:cond_cha_create_time_end;not null" json:"cond_cha_create_time_end"`
	StatusFlag             int32  `gorm:"column:status_flag;not null" json:"status_flag"`
	Title                  string `gorm:"column:title;not null" json:"title"`
	RangeSection           int32  `gorm:"column:range_section;not null" json:"range_section"`
	ReasonEtc              string `gorm:"column:reason_etc;not null" json:"reason_etc"`
	ReasonStop             string `gorm:"column:reason_stop;not null" json:"reason_stop"`
	PosFlag                string `gorm:"column:pos_flag;not null;default:0" json:"pos_flag"`
}

// TableName LimitedShopManager's table name
func (*LimitedShopManager) TableName() string {
	return TableNameLimitedShopManager
}
