// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLimitCreateCharacterIP = "limit_create_character_ip"

// LimitCreateCharacterIP mapped from table <limit_create_character_ip>
type LimitCreateCharacterIP struct {
	IP             int32     `gorm:"column:ip;primaryKey" json:"ip"`
	IPStr          string    `gorm:"column:ip_str;not null" json:"ip_str"`
	LastAccessTime time.Time `gorm:"column:last_access_time;not null" json:"last_access_time"`
	Count_         int32     `gorm:"column:count;not null" json:"count"`
	LastAccessMid  int32     `gorm:"column:last_access_mid;not null" json:"last_access_mid"`
}

// TableName LimitCreateCharacterIP's table name
func (*LimitCreateCharacterIP) TableName() string {
	return TableNameLimitCreateCharacterIP
}
