// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMWithdraw = "m_withdraw"

// MWithdraw mapped from table <m_withdraw>
type MWithdraw struct {
	MID       int32     `gorm:"column:m_id;primaryKey;autoIncrement:true" json:"m_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	UserName  string    `gorm:"column:user_name;not null" json:"user_name"`
	FirstSsn  string    `gorm:"column:first_ssn;not null" json:"first_ssn"`
	SecondSsn string    `gorm:"column:second_ssn;not null" json:"second_ssn"`
	Passwd    string    `gorm:"column:passwd;not null" json:"passwd"`
	MobileNo  string    `gorm:"column:mobile_no;not null" json:"mobile_no"`
	RegDate   int32     `gorm:"column:reg_date;not null" json:"reg_date"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	QNo       int32     `gorm:"column:q_no;not null" json:"q_no"`
	QAnswer   string    `gorm:"column:q_answer;not null" json:"q_answer"`
	UpdtDate  time.Time `gorm:"column:updt_date;not null;default:CURRENT_TIMESTAMP" json:"updt_date"`
	State     int32     `gorm:"column:state;not null" json:"state"`
	WType     int32     `gorm:"column:w_type;not null" json:"w_type"`
	WCause    string    `gorm:"column:w_cause;not null" json:"w_cause"`
	WDate     int32     `gorm:"column:w_date;not null" json:"w_date"`
	Nickname  string    `gorm:"column:nickname;not null" json:"nickname"`
}

// TableName MWithdraw's table name
func (*MWithdraw) TableName() string {
	return TableNameMWithdraw
}
