// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaxCountPvp = "max_count_pvp"

// MaxCountPvp mapped from table <max_count_pvp>
type MaxCountPvp struct {
	ServerInfo int32     `gorm:"column:server_info;not null" json:"server_info"`
	McMax      int32     `gorm:"column:mc_max;not null" json:"mc_max"`
	McDate     time.Time `gorm:"column:mc_date;not null" json:"mc_date"`
}

// TableName MaxCountPvp's table name
func (*MaxCountPvp) TableName() string {
	return TableNameMaxCountPvp
}
