// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaxCountChannel = "max_count_channel"

// MaxCountChannel mapped from table <max_count_channel>
type MaxCountChannel struct {
	ServerInfo    int32     `gorm:"column:server_info;not null" json:"server_info"`
	GcChanneltype string    `gorm:"column:gc_channeltype;not null" json:"gc_channeltype"`
	McMax         int32     `gorm:"column:mc_max;not null" json:"mc_max"`
	McDate        time.Time `gorm:"column:mc_date;not null" json:"mc_date"`
}

// TableName MaxCountChannel's table name
func (*MaxCountChannel) TableName() string {
	return TableNameMaxCountChannel
}
