// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaxCount = "max_count"

// MaxCount mapped from table <max_count>
type MaxCount struct {
	ServerInfo int32     `gorm:"column:server_info;not null" json:"server_info"`
	McMax      int32     `gorm:"column:mc_max;not null" json:"mc_max"`
	McDate     time.Time `gorm:"column:mc_date;not null" json:"mc_date"`
}

// TableName MaxCount's table name
func (*MaxCount) TableName() string {
	return TableNameMaxCount
}
