// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberMile = "member_miles"

// MemberMile mapped from table <member_miles>
type MemberMile struct {
	MID        int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	Miles      int32 `gorm:"column:miles;not null" json:"miles"`
	DailyMiles int32 `gorm:"column:daily_miles;not null" json:"daily_miles"`
}

// TableName MemberMile's table name
func (*MemberMile) TableName() string {
	return TableNameMemberMile
}
