// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberHandicap = "member_handicap"

// MemberHandicap mapped from table <member_handicap>
type MemberHandicap struct {
	EventID       int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	CapType       int32     `gorm:"column:cap_type;primaryKey" json:"cap_type"`
	ServerID      int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	MID           int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	StartTime     time.Time `gorm:"column:start_time;primaryKey" json:"start_time"`
	EndTime       time.Time `gorm:"column:end_time;not null" json:"end_time"`
	HandicapValue int32     `gorm:"column:handicap_value;not null" json:"handicap_value"`
}

// TableName MemberHandicap's table name
func (*MemberHandicap) TableName() string {
	return TableNameMemberHandicap
}
