// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberPasswdMod = "member_passwd_mod"

// MemberPasswdMod mapped from table <member_passwd_mod>
type MemberPasswdMod struct {
	MID       int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	FirstTime time.Time `gorm:"column:first_time;not null" json:"first_time"`
	LastTime  time.Time `gorm:"column:last_time;not null" json:"last_time"`
	Cnt       int32     `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName MemberPasswdMod's table name
func (*MemberPasswdMod) TableName() string {
	return TableNameMemberPasswdMod
}
