// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberBroadcast = "member_broadcast"

// MemberBroadcast mapped from table <member_broadcast>
type MemberBroadcast struct {
	EventID    int32     `gorm:"column:event_id;primaryKey" json:"event_id"`
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	ServerID   int32     `gorm:"column:server_id;primaryKey" json:"server_id"`
	CharacNo   int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	CharacName string    `gorm:"column:charac_name;not null" json:"charac_name"`
	StartTime  time.Time `gorm:"column:start_time;primaryKey" json:"start_time"`
	EndTime    time.Time `gorm:"column:end_time;not null" json:"end_time"`
}

// TableName MemberBroadcast's table name
func (*MemberBroadcast) TableName() string {
	return TableNameMemberBroadcast
}
