// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberPunishHackHistory = "member_punish_hack_history"

// MemberPunishHackHistory mapped from table <member_punish_hack_history>
type MemberPunishHackHistory struct {
	MID      int32  `gorm:"column:m_id;not null" json:"m_id"`
	OccTime  int32  `gorm:"column:occ_time;not null" json:"occ_time"`
	Period   int32  `gorm:"column:period;not null" json:"period"`
	NowFlag  int32  `gorm:"column:now_flag;not null" json:"now_flag"`
	AutoFlag int32  `gorm:"column:auto_flag;not null" json:"auto_flag"`
	Reason   string `gorm:"column:reason;not null" json:"reason"`
}

// TableName MemberPunishHackHistory's table name
func (*MemberPunishHackHistory) TableName() string {
	return TableNameMemberPunishHackHistory
}
