// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberJoinInfo = "member_join_info"

// MemberJoinInfo mapped from table <member_join_info>
type MemberJoinInfo struct {
	MID            int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	RegDate        int32  `gorm:"column:reg_date;not null" json:"reg_date"`
	IP             string `gorm:"column:ip;not null" json:"ip"`
	ContryCode     int32  `gorm:"column:contry_code;not null" json:"contry_code"`
	LoginTime      int32  `gorm:"column:login_time;not null" json:"login_time"`
	ErrorType      int32  `gorm:"column:error_type;not null" json:"error_type"`
	LoginIP        string `gorm:"column:login_ip;not null" json:"login_ip"`
	GameUseHistory int32  `gorm:"column:game_use_history;not null" json:"game_use_history"`
}

// TableName MemberJoinInfo's table name
func (*MemberJoinInfo) TableName() string {
	return TableNameMemberJoinInfo
}
