// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberInfoDetail = "member_info_detail"

// MemberInfoDetail mapped from table <member_info_detail>
type MemberInfoDetail struct {
	MID           int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	Zipcode       string    `gorm:"column:zipcode;not null" json:"zipcode"`
	Address       string    `gorm:"column:address;not null" json:"address"`
	AddressDetail string    `gorm:"column:address_detail;not null" json:"address_detail"`
	OccDate       time.Time `gorm:"column:occ_date;not null" json:"occ_date"`
}

// TableName MemberInfoDetail's table name
func (*MemberInfoDetail) TableName() string {
	return TableNameMemberInfoDetail
}
