// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberLioness = "member_lioness"

// MemberLioness mapped from table <member_lioness>
type MemberLioness struct {
	UserID string `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName MemberLioness's table name
func (*MemberLioness) TableName() string {
	return TableNameMemberLioness
}
