// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberAbnomal = "member_abnomal"

// MemberAbnomal mapped from table <member_abnomal>
type MemberAbnomal struct {
	UserID       string `gorm:"column:user_id;primaryKey" json:"user_id"`
	OverlabCount int32  `gorm:"column:overlab_count;not null" json:"overlab_count"`
}

// TableName MemberAbnomal's table name
func (*MemberAbnomal) TableName() string {
	return TableNameMemberAbnomal
}
