// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberPunishHack = "member_punish_hack"

// MemberPunishHack mapped from table <member_punish_hack>
type MemberPunishHack struct {
	MID      int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime  int32  `gorm:"column:occ_time;not null" json:"occ_time"`
	Period   int32  `gorm:"column:period;not null" json:"period"`
	NowFlag  int32  `gorm:"column:now_flag;not null" json:"now_flag"`
	AutoFlag int32  `gorm:"column:auto_flag;not null" json:"auto_flag"`
	Reason   string `gorm:"column:reason;not null" json:"reason"`
	HackIP   string `gorm:"column:hack_ip;not null" json:"hack_ip"`
}

// TableName MemberPunishHack's table name
func (*MemberPunishHack) TableName() string {
	return TableNameMemberPunishHack
}
