// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberMouseSm = "member_mouse_sms"

// MemberMouseSm mapped from table <member_mouse_sms>
type MemberMouseSm struct {
	MID     int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
	Cnt     int32     `gorm:"column:cnt;not null" json:"cnt"`
}

// TableName MemberMouseSm's table name
func (*MemberMouseSm) TableName() string {
	return TableNameMemberMouseSm
}
