// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNewsBb = "news_bbs"

// NewsBb mapped from table <news_bbs>
type NewsBb struct {
	BbsCode  int32  `gorm:"column:bbs_code;primaryKey" json:"bbs_code"`
	EmphYn   bool   `gorm:"column:emph_yn;primaryKey" json:"emph_yn"`
	No       int32  `gorm:"column:no;primaryKey;autoIncrement:true" json:"no"`
	UserID   string `gorm:"column:user_id;not null" json:"user_id"`
	RegDate  int32  `gorm:"column:reg_date;not null" json:"reg_date"`
	HTMLYn   bool   `gorm:"column:html_yn" json:"html_yn"`
	Subject  string `gorm:"column:subject;not null" json:"subject"`
	Body     string `gorm:"column:body;not null" json:"body"`
	Hits     int32  `gorm:"column:hits;not null" json:"hits"`
	PrevNo   int32  `gorm:"column:prev_no;not null" json:"prev_no"`
	NextNo   int32  `gorm:"column:next_no;not null" json:"next_no"`
	UpdtDate int32  `gorm:"column:updt_date" json:"updt_date"`
	UseYn    bool   `gorm:"column:use_yn;not null;default:1" json:"use_yn"`
	FileName string `gorm:"column:file_name" json:"file_name"`
}

// TableName NewsBb's table name
func (*NewsBb) TableName() string {
	return TableNameNewsBb
}
