// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNotice = "notice"

// Notice mapped from table <notice>
type Notice struct {
	BbsName     string  `gorm:"column:bbs_name;not null" json:"bbs_name"`
	No          int32   `gorm:"column:no;not null" json:"no"`
	Category    int32   `gorm:"column:category;not null" json:"category"`
	MNickname   string  `gorm:"column:m_nickname;not null" json:"m_nickname"`
	MID         int32   `gorm:"column:m_id;not null" json:"m_id"`
	MUserID     string  `gorm:"column:m_user_id;not null" json:"m_user_id"`
	MSex        string  `gorm:"column:m_sex;not null;default:m" json:"m_sex"`
	Title       string  `gorm:"column:title;not null" json:"title"`
	CreateDay   int32   `gorm:"column:create_day;not null" json:"create_day"`
	Comment     int32   `gorm:"column:comment;not null" json:"comment"`
	View        int32   `gorm:"column:view;not null" json:"view"`
	Recom       int32   `gorm:"column:recom;not null" json:"recom"`
	Adorn       int32   `gorm:"column:adorn;not null" json:"adorn"`
	AdornColor1 int32   `gorm:"column:adorn_color1;not null" json:"adorn_color1"`
	AdornColor2 int32   `gorm:"column:adorn_color2;not null" json:"adorn_color2"`
	Depth       int32   `gorm:"column:depth;not null" json:"depth"`
	Sequence    float64 `gorm:"column:sequence;not null" json:"sequence"`
	Content     string  `gorm:"column:content;not null" json:"content"`
	ContentType string  `gorm:"column:content_type;not null;default:br" json:"content_type"`
	IP          string  `gorm:"column:ip;not null" json:"ip"`
	Ring        int32   `gorm:"column:ring;not null" json:"ring"`
	Sms         string  `gorm:"column:sms;not null;default:n" json:"sms"`
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
