// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePasswdModEntry = "passwd_mod_entry"

// PasswdModEntry mapped from table <passwd_mod_entry>
type PasswdModEntry struct {
	MID       int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	OccTime   time.Time `gorm:"column:occ_time;primaryKey" json:"occ_time"`
	IP        string    `gorm:"column:ip;not null" json:"ip"`
	PrePasswd string    `gorm:"column:pre_passwd;not null" json:"pre_passwd"`
}

// TableName PasswdModEntry's table name
func (*PasswdModEntry) TableName() string {
	return TableNamePasswdModEntry
}
