// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePswdQstion = "pswd_qstion"

// PswdQstion mapped from table <pswd_qstion>
type PswdQstion struct {
	QNo   int32  `gorm:"column:q_no;primaryKey" json:"q_no"`
	QText string `gorm:"column:q_text;not null" json:"q_text"`
}

// TableName PswdQstion's table name
func (*PswdQstion) TableName() string {
	return TableNamePswdQstion
}
