// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePuUserList = "pu_user_list"

// PuUserList mapped from table <pu_user_list>
type PuUserList struct {
	MID int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
}

// TableName PuUserList's table name
func (*PuUserList) TableName() string {
	return TableNamePuUserList
}
