// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSlangListName = "slang_list_name"

// SlangListName mapped from table <slang_list_name>
type SlangListName struct {
	Slang string `gorm:"column:slang;primaryKey" json:"slang"`
}

// TableName SlangListName's table name
func (*SlangListName) TableName() string {
	return TableNameSlangListName
}
