// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_users"

// SysUser mapped from table <sys_users>
type SysUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UpdatedBy string         `gorm:"column:updated_by;default:系统自动;comment:更新操作人" json:"updated_by"`                                                                       // 更新操作人
	UUID      string         `gorm:"column:uuid;comment:用户UUID" json:"uuid"`                                                                                               // 用户UUID
	Username  string         `gorm:"column:username;comment:用户登录名" json:"username"`                                                                                        // 用户登录名
	Password  string         `gorm:"column:password;comment:用户登录密码" json:"password"`                                                                                       // 用户登录密码
	NickName  string         `gorm:"column:nick_name;default:系统用户;comment:用户昵称" json:"nick_name"`                                                                          // 用户昵称
	HeaderImg string         `gorm:"column:header_img;default:https://huaduogiegie.oss-cn-shanghai.aliyuncs.com/picgo/202305281629232.png;comment:用户头像" json:"header_img"` // 用户头像
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
