// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUnderBillingConfirm = "under_billing_confirm"

// UnderBillingConfirm mapped from table <under_billing_confirm>
type UnderBillingConfirm struct {
	MID               int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	ParentName        string `gorm:"column:parent_name;not null" json:"parent_name"`
	ParentJumin       int64  `gorm:"column:parent_jumin;not null" json:"parent_jumin"`
	ParentPhone1      int32  `gorm:"column:parent_phone1;not null" json:"parent_phone1"`
	ParentPhone2      int32  `gorm:"column:parent_phone2;not null" json:"parent_phone2"`
	ParentPhone3      int32  `gorm:"column:parent_phone3;not null" json:"parent_phone3"`
	ParentEmail       string `gorm:"column:parent_email;not null" json:"parent_email"`
	ParentConsentType int32  `gorm:"column:parent_consent_type;not null" json:"parent_consent_type"`
	CreateDate        int32  `gorm:"column:create_date;not null" json:"create_date"`
	ConsentDate       int32  `gorm:"column:consent_date;not null" json:"consent_date"`
	ConsentYn         int32  `gorm:"column:consent_yn;not null" json:"consent_yn"`
}

// TableName UnderBillingConfirm's table name
func (*UnderBillingConfirm) TableName() string {
	return TableNameUnderBillingConfirm
}
