// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChDungeonList = "ch_dungeon_list"

// ChDungeonList mapped from table <ch_dungeon_list>
type ChDungeonList struct {
	KindName  string `gorm:"column:kind_name;not null" json:"kind_name"`
	DungeonID int32  `gorm:"column:dungeon_id;not null" json:"dungeon_id"`
}

// TableName ChDungeonList's table name
func (*ChDungeonList) TableName() string {
	return TableNameChDungeonList
}
