// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChDungeonDatum = "ch_dungeon_data"

// ChDungeonDatum mapped from table <ch_dungeon_data>
type ChDungeonDatum struct {
	KindName    string `gorm:"column:kind_name;not null" json:"kind_name"`
	DungeonName string `gorm:"column:dungeon_name;not null" json:"dungeon_name"`
}

// TableName ChDungeonDatum's table name
func (*ChDungeonDatum) TableName() string {
	return TableNameChDungeonDatum
}
