// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChGcInfo = "ch_gc_info"

// ChGcInfo mapped from table <ch_gc_info>
type ChGcInfo struct {
	GroupName string `gorm:"column:group_name;not null" json:"group_name"`
	GroupGcNo string `gorm:"column:group_gc_no;not null" json:"group_gc_no"`
}

// TableName ChGcInfo's table name
func (*ChGcInfo) TableName() string {
	return TableNameChGcInfo
}
