// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChScriptVersion = "ch_script_version"

// ChScriptVersion mapped from table <ch_script_version>
type ChScriptVersion struct {
	ScriptVersion string `gorm:"column:script_version;not null" json:"script_version"`
}

// TableName ChScriptVersion's table name
func (*ChScriptVersion) TableName() string {
	return TableNameChScriptVersion
}
