// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChServerDatum = "ch_server_data"

// ChServerDatum mapped from table <ch_server_data>
type ChServerDatum struct {
	ID            int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServerID      int32   `gorm:"column:server_id;not null" json:"server_id"`
	IsUse         int32   `gorm:"column:is_use;not null" json:"is_use"`
	ChannelNumber int32   `gorm:"column:channel_number;not null" json:"channel_number"`
	ChannelName   string  `gorm:"column:channel_name;not null" json:"channel_name"`
	ChannelKind   int32   `gorm:"column:channel_kind;not null" json:"channel_kind"`
	KindName      string  `gorm:"column:kind_name;not null" json:"kind_name"`
	ExpRate       float32 `gorm:"column:exp_rate;not null" json:"exp_rate"`
	Exp1          float32 `gorm:"column:exp_1;not null" json:"exp_1"`
	Exp2          float32 `gorm:"column:exp_2;not null" json:"exp_2"`
	Exp3          float32 `gorm:"column:exp_3;not null" json:"exp_3"`
	Exp4          float32 `gorm:"column:exp_4;not null" json:"exp_4"`
	Exp5          float32 `gorm:"column:exp_5;not null" json:"exp_5"`
	Exp6          float32 `gorm:"column:exp_6;not null" json:"exp_6"`
	Exp7          float32 `gorm:"column:exp_7;not null" json:"exp_7"`
	Exp8          float32 `gorm:"column:exp_8;not null" json:"exp_8"`
	Exp9          float32 `gorm:"column:exp_9;not null" json:"exp_9"`
	Exp10         float32 `gorm:"column:exp_10;not null" json:"exp_10"`
}

// TableName ChServerDatum's table name
func (*ChServerDatum) TableName() string {
	return TableNameChServerDatum
}
