// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacInvenExpand = "charac_inven_expand"

// CharacInvenExpand mapped from table <charac_inven_expand>
type CharacInvenExpand struct {
	CharacNo         int32  `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	Cargo            []byte `gorm:"column:cargo;not null" json:"cargo"`
	CargoCapacity    int32  `gorm:"column:cargo_capacity;not null" json:"cargo_capacity"`
	Jewel            []byte `gorm:"column:jewel;not null" json:"jewel"`
	CurrentEquipslot string `gorm:"column:current_equipslot;not null" json:"current_equipslot"`
	SwitchEquipslot  []byte `gorm:"column:switch_equipslot;not null" json:"switch_equipslot"`
	ExpandEquipslot  []byte `gorm:"column:expand_equipslot;not null" json:"expand_equipslot"`
	RedeemInfo       []byte `gorm:"column:redeem_info;not null" json:"redeem_info"`
}

// TableName CharacInvenExpand's table name
func (*CharacInvenExpand) TableName() string {
	return TableNameCharacInvenExpand
}
