// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCharacBlackInfo = "charac_black_info"

// CharacBlackInfo mapped from table <charac_black_info>
type CharacBlackInfo struct {
	CharacNo         int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	BlackPoint       int32     `gorm:"column:black_point;not null" json:"black_point"`
	OffsetPoint      int32     `gorm:"column:offset_point;not null" json:"offset_point"`
	ProblemChildTime time.Time `gorm:"column:problem_child_time;not null" json:"problem_child_time"`
}

// TableName CharacBlackInfo's table name
func (*CharacBlackInfo) TableName() string {
	return TableNameCharacBlackInfo
}
