// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCharacEventItem = "charac_event_items"

// CharacEventItem mapped from table <charac_event_items>
type CharacEventItem struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CharacNo   int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	ItID       int32     `gorm:"column:it_id;not null" json:"it_id"`
	EventCode  int32     `gorm:"column:event_code;not null" json:"event_code"`
	RegTime    time.Time `gorm:"column:reg_time;not null" json:"reg_time"`
	DeleteTime time.Time `gorm:"column:delete_time;not null" json:"delete_time"`
	DeleteFlag int32     `gorm:"column:delete_flag;not null" json:"delete_flag"`
	StackCount int32     `gorm:"column:stack_count;not null" json:"stack_count"`
}

// TableName CharacEventItem's table name
func (*CharacEventItem) TableName() string {
	return TableNameCharacEventItem
}
