// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacAdvanceAltar = "charac_advance_altar"

// CharacAdvanceAltar mapped from table <charac_advance_altar>
type CharacAdvanceAltar struct {
	CharacNo            int32  `gorm:"column:charac_no;primaryKey;comment:ﾄｳｸｯﾅﾍｹ?｣" json:"charac_no"`                                                     // ﾄｳｸｯﾅﾍｹ?｣
	RidableID           int32  `gorm:"column:ridable_id;primaryKey;comment:ｺｯｽﾅｸ?ｺﾅﾍ ｾﾆﾀﾌｵ" json:"ridable_id"`                                             // ｺｯｽﾅｸ?ｺﾅﾍ ｾﾆﾀﾌｵ
	TicketFree          int32  `gorm:"column:ticket_free;not null;comment:ｹｫｷ眤ﾔﾀ螻ﾇ(ｻ鄂ﾅﾀﾇ ﾃﾊｴ??ﾃｳｷｳ ｸﾅﾀﾏ ﾃ､ｿ??" json:"ticket_free"`                         // ｹｫｷ眤ﾔﾀ螻ﾇ(ｻ鄂ﾅﾀﾇ ﾃﾊｴ??ﾃｳｷｳ ｸﾅﾀﾏ ﾃ､ｿ??
	TicketCera          int32  `gorm:"column:ticket_cera;not null;comment:ｼｼｶ?･ｿ｡ｼｭ ｱｸｸﾅﾇﾑ ﾀｯｷ眤ﾔﾀ螻ﾇ" json:"ticket_cera"`                                   // ｼｼｶ?･ｿ｡ｼｭ ｱｸｸﾅﾇﾑ ﾀｯｷ眤ﾔﾀ螻ﾇ
	StarGame            int32  `gorm:"column:star_game;not null;comment:ｽｺﾅﾗﾀﾌﾁ?ﾅｬｸｮｾ?ｺｸｻ?ｸｷﾎ ｹﾞﾀｺ star (ﾁ?｡ﾇﾏｰ?ｰｨｼﾒ ｾ?ｽ)" json:"star_game"`               // ｽｺﾅﾗﾀﾌﾁ?ﾅｬｸｮｾ?ｺｸｻ?ｸｷﾎ ｹﾞﾀｺ star (ﾁ?｡ﾇﾏｰ?ｰｨｼﾒ ｾ?ｽ)
	StarCera            int32  `gorm:"column:star_cera;not null;comment:ｼｼｶ?･ｿ｡ｼｭ ｱｸｸﾅﾇﾑ ﾀｯｷ?star(ﾁ?｡ﾇﾏｰ?ｰｨｼﾒ ｾ?ｽ)" json:"star_cera"`                      // ｼｼｶ?･ｿ｡ｼｭ ｱｸｸﾅﾇﾑ ﾀｯｷ?star(ﾁ?｡ﾇﾏｰ?ｰｨｼﾒ ｾ?ｽ)
	StarUsable          int32  `gorm:"column:star_usable;not null;comment:ｻ鄙?｡ｴﾉﾇﾑ star (=ｻ鄙?ﾏｰ?ｳｲﾀｺ star)" json:"star_usable"`                            // ｻ鄙?｡ｴﾉﾇﾑ star (=ｻ鄙?ﾏｰ?ｳｲﾀｺ star)
	SurvivalBest        int32  `gorm:"column:survival_best;not null;comment:ｼｭｹﾙﾀﾌｹ??蠢｡ｼｭ ﾅｬｸｮｾ?ﾑ ﾃﾖｴ?ｽｺﾅﾗﾀﾌﾁ??｣" json:"survival_best"`                    // ｼｭｹﾙﾀﾌｹ??蠢｡ｼｭ ﾅｬｸｮｾ?ﾑ ﾃﾖｴ?ｽｺﾅﾗﾀﾌﾁ??｣
	StarResetCount      int32  `gorm:"column:star_reset_count;not null;comment:starｸｦ ﾃﾊｱ篳ｭﾇﾑ ﾈｸｼ?ｱ篳ｹ:ﾃﾊｱ篳ｭ ﾈｽｼ?｡ ｵ??ｺ??ﾌ ｴﾙｸｧ)" json:"star_reset_count"`  // starｸｦ ﾃﾊｱ篳ｭﾇﾑ ﾈｸｼ?ｱ篳ｹ:ﾃﾊｱ篳ｭ ﾈｽｼ?｡ ｵ??ｺ??ﾌ ｴﾙｸｧ)
	IsUnlockStageEffect int32  `gorm:"column:is_unlock_stage_effect;not null;comment:ｽｺﾅﾗﾀﾌﾁ?unlock ﾀﾌﾆ衄ｮｸｦ ｺｸｿｩﾁ狎ﾟ ﾇﾏｴﾂﾁ?" json:"is_unlock_stage_effect"` // ｽｺﾅﾗﾀﾌﾁ?unlock ﾀﾌﾆ衄ｮｸｦ ｺｸｿｩﾁ狎ﾟ ﾇﾏｴﾂﾁ?
	StageList           []byte `gorm:"column:stage_list;not null;comment:ﾅｬｸｮｾ?ﾑ, ﾀﾔﾀ?ﾇﾒ ｼ?ﾀﾖｴﾂ ｽｺﾅﾗﾀﾌﾁ?ｮｽｺﾆｮ" json:"stage_list"`                          // ﾅｬｸｮｾ?ﾑ, ﾀﾔﾀ?ﾇﾒ ｼ?ﾀﾖｴﾂ ｽｺﾅﾗﾀﾌﾁ?ｮｽｺﾆｮ
	SlotList            []byte `gorm:"column:slot_list;not null;comment:ｽｽｷﾔ ｸｮｽｺﾆｮ" json:"slot_list"`                                                     // ｽｽｷﾔ ｸｮｽｺﾆｮ
	BuyItemList         []byte `gorm:"column:buy_item_list;not null;comment:ｾ?ﾗｷｹﾀﾌｵ?ｻ?｡ｿ｡ｼｭ ｱｸｸﾅﾇﾑ ｾﾆﾀﾌﾅﾛ ｸｮｽｺﾆｮ" json:"buy_item_list"`                   // ｾ?ﾗｷｹﾀﾌｵ?ｻ?｡ｿ｡ｼｭ ｱｸｸﾅﾇﾑ ｾﾆﾀﾌﾅﾛ ｸｮｽｺﾆｮ
	RewardList          []byte `gorm:"column:reward_list;not null;comment:ｾ??ｺｸｻ?ｸｮｽｺﾆｮ" json:"reward_list"`                                               // ｾ??ｺｸｻ?ｸｮｽｺﾆｮ
}

// TableName CharacAdvanceAltar's table name
func (*CharacAdvanceAltar) TableName() string {
	return TableNameCharacAdvanceAltar
}
