// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCharacBlackList = "charac_black_list"

// CharacBlackList mapped from table <charac_black_list>
type CharacBlackList struct {
	MID        int32     `gorm:"column:m_id;primaryKey" json:"m_id"`
	CharacNo   int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	CharacName string    `gorm:"column:charac_name;not null" json:"charac_name"`
	OccTime    time.Time `gorm:"column:occ_time;not null" json:"occ_time"`
}

// TableName CharacBlackList's table name
func (*CharacBlackList) TableName() string {
	return TableNameCharacBlackList
}
