// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComboSkill = "combo_skill"

// ComboSkill mapped from table <combo_skill>
type ComboSkill struct {
	CharacNo int32 `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	ComboIdx int32 `gorm:"column:combo_idx;primaryKey" json:"combo_idx"`
	Value1   int32 `gorm:"column:value1;not null" json:"value1"`
	Value2   int32 `gorm:"column:value2;not null" json:"value2"`
	Value3   int32 `gorm:"column:value3;not null" json:"value3"`
	Value4   int32 `gorm:"column:value4;not null" json:"value4"`
	Value5   int32 `gorm:"column:value5;not null" json:"value5"`
	Value6   int32 `gorm:"column:value6;not null" json:"value6"`
}

// TableName ComboSkill's table name
func (*ComboSkill) TableName() string {
	return TableNameComboSkill
}
