// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCreatureItem = "creature_items"

// CreatureItem mapped from table <creature_items>
type CreatureItem struct {
	UIID         int32     `gorm:"column:ui_id;primaryKey;autoIncrement:true" json:"ui_id"`
	CharacNo     int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	Slot         int32     `gorm:"column:slot;not null" json:"slot"`
	ItID         int32     `gorm:"column:it_id;not null" json:"it_id"`
	RegDate      time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Stomach      int32     `gorm:"column:stomach;not null" json:"stomach"`
	Exp          int32     `gorm:"column:exp;not null" json:"exp"`
	Endurance    int32     `gorm:"column:endurance;not null" json:"endurance"`
	CreatureType int32     `gorm:"column:creature_type;not null" json:"creature_type"`
	NoCharge     int32     `gorm:"column:no_charge;not null" json:"no_charge"`
	Stat         int32     `gorm:"column:stat;not null" json:"stat"`
	ItemLockKey  int32     `gorm:"column:item_lock_key;not null" json:"item_lock_key"`
	IpgAgencyNo  string    `gorm:"column:ipg_agency_no;not null" json:"ipg_agency_no"`
	ExpireDate   time.Time `gorm:"column:expire_date;not null;default:9999-12-31 23:59:59" json:"expire_date"`
	DeleteDate   time.Time `gorm:"column:delete_date;not null;default:9999-12-31 23:59:59" json:"delete_date"`
}

// TableName CreatureItem's table name
func (*CreatureItem) TableName() string {
	return TableNameCreatureItem
}
