// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDblabAvatarSocket = "dblab_avatar_socket"

// DblabAvatarSocket mapped from table <dblab_avatar_socket>
type DblabAvatarSocket struct {
	ItID        int32  `gorm:"column:it_id;primaryKey" json:"it_id"`
	JewelSocket string `gorm:"column:jewel_socket" json:"jewel_socket"`
}

// TableName DblabAvatarSocket's table name
func (*DblabAvatarSocket) TableName() string {
	return TableNameDblabAvatarSocket
}
