// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFairPvpScore = "fair_pvp_score"

// FairPvpScore mapped from table <fair_pvp_score>
type FairPvpScore struct {
	CharacNo         int32     `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	PrivateWin       int32     `gorm:"column:private_win;not null" json:"private_win"`
	PrivateLose      int32     `gorm:"column:private_lose;not null" json:"private_lose"`
	PrivateDraw      int32     `gorm:"column:private_draw;not null" json:"private_draw"`
	RelayBattleWin   int32     `gorm:"column:relay_battle_win;not null" json:"relay_battle_win"`
	RelayBattleLose  int32     `gorm:"column:relay_battle_lose;not null" json:"relay_battle_lose"`
	RelayBattleDraw  int32     `gorm:"column:relay_battle_draw;not null" json:"relay_battle_draw"`
	RelayBattle2kill int32     `gorm:"column:relay_battle_2kill;not null" json:"relay_battle_2kill"`
	SuccessiveWin    int32     `gorm:"column:successive_win;not null" json:"successive_win"`
	JobScore         []byte    `gorm:"column:job_score" json:"job_score"`
	RelayBattle3kill int32     `gorm:"column:relay_battle_3kill" json:"relay_battle_3kill"`
	MaxSuccessiveWin int32     `gorm:"column:max_successive_win" json:"max_successive_win"`
	DailyPlayCount   int32     `gorm:"column:daily_play_count;not null" json:"daily_play_count"`
	LastPlayTime     time.Time `gorm:"column:last_play_time;not null" json:"last_play_time"`
	PvpMissionInfo   []byte    `gorm:"column:pvp_mission_info" json:"pvp_mission_info"`
	GiveItem         int32     `gorm:"column:give_item;not null" json:"give_item"`
}

// TableName FairPvpScore's table name
func (*FairPvpScore) TableName() string {
	return TableNameFairPvpScore
}
