// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	CharacNo          int32  `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	Money             int32  `gorm:"column:money;not null" json:"money"`
	Coin              int32  `gorm:"column:coin;not null" json:"coin"`
	Inventory         []byte `gorm:"column:inventory;not null" json:"inventory"`
	Equipslot         []byte `gorm:"column:equipslot;not null" json:"equipslot"`
	PayCoin           int32  `gorm:"column:pay_coin;not null" json:"pay_coin"`
	EventCoin         int32  `gorm:"column:event_coin;not null" json:"event_coin"`
	Creature          []byte `gorm:"column:creature;not null" json:"creature"`
	CreatureFlag      int32  `gorm:"column:creature_flag;not null" json:"creature_flag"`
	Katagaki          []byte `gorm:"column:katagaki;not null" json:"katagaki"`
	InventoryCapacity int32  `gorm:"column:inventory_capacity;not null" json:"inventory_capacity"`
	AvatarCoin        int32  `gorm:"column:avatar_coin;not null" json:"avatar_coin"`
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
