// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLetter = "letter"

// Letter mapped from table <letter>
type Letter struct {
	LetterID       int32     `gorm:"column:letter_id;primaryKey;autoIncrement:true" json:"letter_id"`
	CharacNo       int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	SendCharacNo   int32     `gorm:"column:send_charac_no;not null" json:"send_charac_no"`
	SendCharacName string    `gorm:"column:send_charac_name;not null" json:"send_charac_name"`
	LetterText     string    `gorm:"column:letter_text;not null" json:"letter_text"`
	RegDate        time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
	Stat           int32     `gorm:"column:stat;not null" json:"stat"`
}

// TableName Letter's table name
func (*Letter) TableName() string {
	return TableNameLetter
}
