// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberAvatarCoin = "member_avatar_coin"

// MemberAvatarCoin mapped from table <member_avatar_coin>
type MemberAvatarCoin struct {
	MID        int32 `gorm:"column:m_id;primaryKey" json:"m_id"`
	AvatarCoin int32 `gorm:"column:avatar_coin;not null" json:"avatar_coin"`
}

// TableName MemberAvatarCoin's table name
func (*MemberAvatarCoin) TableName() string {
	return TableNameMemberAvatarCoin
}
