// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkillLethe = "skill_lethe"

// SkillLethe mapped from table <skill_lethe>
type SkillLethe struct {
	MID       int32  `gorm:"column:m_id;primaryKey" json:"m_id"`
	CharacNo  int32  `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	SkillSlot []byte `gorm:"column:skill_slot;not null" json:"skill_slot"`
	Flag      int32  `gorm:"column:flag;not null" json:"flag"`
}

// TableName SkillLethe's table name
func (*SkillLethe) TableName() string {
	return TableNameSkillLethe
}
