// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkillFairPvp = "skill_fair_pvp"

// SkillFairPvp mapped from table <skill_fair_pvp>
type SkillFairPvp struct {
	CharacNo          int32  `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	RemainSp          int32  `gorm:"column:remain_sp;not null" json:"remain_sp"`
	SkillSlot         []byte `gorm:"column:skill_slot" json:"skill_slot"`
	SpGarbage         int32  `gorm:"column:sp_garbage;not null" json:"sp_garbage"`
	UsedSp            int32  `gorm:"column:used_sp;not null" json:"used_sp"`
	SkillSlotLethe    []byte `gorm:"column:skill_slot_lethe" json:"skill_slot_lethe"`
	LetheFlag         int32  `gorm:"column:lethe_flag;not null" json:"lethe_flag"`
	RemainSp2nd       int32  `gorm:"column:remain_sp_2nd;not null" json:"remain_sp_2nd"`
	SkillSlot2nd      []byte `gorm:"column:skill_slot_2nd" json:"skill_slot_2nd"`
	SkillSlotLethe2nd []byte `gorm:"column:skill_slot_lethe_2nd" json:"skill_slot_lethe_2nd"`
	LetheFlag2nd      int32  `gorm:"column:lethe_flag_2nd;not null" json:"lethe_flag_2nd"`
	RemainSfp1st      int32  `gorm:"column:remain_sfp_1st;not null" json:"remain_sfp_1st"`
	RemainSfp2nd      int32  `gorm:"column:remain_sfp_2nd;not null" json:"remain_sfp_2nd"`
	SkillCommand      []byte `gorm:"column:skill_command" json:"skill_command"`
	ScriptVersion     int32  `gorm:"column:script_version;not null" json:"script_version"`
}

// TableName SkillFairPvp's table name
func (*SkillFairPvp) TableName() string {
	return TableNameSkillFairPvp
}
