// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkill = "skill"

// Skill mapped from table <skill>
type Skill struct {
	CharacNo          int32  `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	RemainSp          int32  `gorm:"column:remain_sp;not null" json:"remain_sp"`
	SkillSlot         []byte `gorm:"column:skill_slot;not null" json:"skill_slot"`
	RequestSp         []byte `gorm:"column:request_sp;not null" json:"request_sp"`
	SpGarbage         int32  `gorm:"column:sp_garbage;not null" json:"sp_garbage"`
	UsedSp            int32  `gorm:"column:used_sp;not null" json:"used_sp"`
	RemainSp2nd       int32  `gorm:"column:remain_sp_2nd;not null" json:"remain_sp_2nd"`
	SkillSlot2nd      []byte `gorm:"column:skill_slot_2nd;not null" json:"skill_slot_2nd"`
	RequestSp2nd      []byte `gorm:"column:request_sp_2nd;not null" json:"request_sp_2nd"`
	SkillSlotLethe    []byte `gorm:"column:skill_slot_lethe;not null" json:"skill_slot_lethe"`
	LetheFlag         int32  `gorm:"column:lethe_flag;not null" json:"lethe_flag"`
	SkillSlotLethe2nd []byte `gorm:"column:skill_slot_lethe_2nd;not null" json:"skill_slot_lethe_2nd"`
	LetheFlag2nd      int32  `gorm:"column:lethe_flag_2nd;not null" json:"lethe_flag_2nd"`
	RemainSfp2nd      int32  `gorm:"column:remain_sfp_2nd;not null" json:"remain_sfp_2nd"`
	RemainSfp1st      int32  `gorm:"column:remain_sfp_1st;not null" json:"remain_sfp_1st"`
	SkillCommand      []byte `gorm:"column:skill_command;not null" json:"skill_command"`
	ScriptVersion     int32  `gorm:"column:script_version;not null" json:"script_version"`
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
