// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserItemsWork = "user_items_work"

// UserItemsWork mapped from table <user_items_work>
type UserItemsWork struct {
	UIID          int32     `gorm:"column:ui_id;not null" json:"ui_id"`
	CharacNo      int32     `gorm:"column:charac_no;not null" json:"charac_no"`
	Slot          int32     `gorm:"column:slot;not null" json:"slot"`
	ItID          int32     `gorm:"column:it_id;not null" json:"it_id"`
	ExpireDate    time.Time `gorm:"column:expire_date;not null" json:"expire_date"`
	ObtainFrom    int32     `gorm:"column:obtain_from" json:"obtain_from"`
	RegDate       time.Time `gorm:"column:reg_date;not null" json:"reg_date"`
	IpgAgencyNo   string    `gorm:"column:ipg_agency_no;not null" json:"ipg_agency_no"`
	AbilityNo     int32     `gorm:"column:ability_no;not null" json:"ability_no"`
	Stat          int32     `gorm:"column:stat;not null" json:"stat"`
	ClearAvatarID int32     `gorm:"column:clear_avatar_id;not null" json:"clear_avatar_id"`
	JewelSocket   []byte    `gorm:"column:jewel_socket;not null" json:"jewel_socket"`
	ItemLockKey   int32     `gorm:"column:item_lock_key;not null" json:"item_lock_key"`
}

// TableName UserItemsWork's table name
func (*UserItemsWork) TableName() string {
	return TableNameUserItemsWork
}
