// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVillageTicket = "village_ticket"

// VillageTicket mapped from table <village_ticket>
type VillageTicket struct {
	CharacNo int32 `gorm:"column:charac_no;primaryKey" json:"charac_no"`
	Village  int32 `gorm:"column:village;primaryKey" json:"village"`
}

// TableName VillageTicket's table name
func (*VillageTicket) TableName() string {
	return TableNameVillageTicket
}
